name: reranked
type: retriever
class_name: Reranked
description: Reranked component
version: 1.0.0
dependencies:
  optional: []
  required: []
config_schema:
  type: object
  properties: {}
use_cases: []
