name: "Legal Document Analysis System"

prompts:
  strategy: "domain_specific"
  domain: "legal"
  config:
    citation_requirements: true
    jurisdiction_awareness: true
    
    templates:
      legal_analysis:
        template: |
          Legal Document Analysis:
          
          Document Context:
          {context}
          
          Query: {question}
          
          Analysis:
          1. Relevant Legal Principles:
          2. Document Provisions:
          3. Legal Implications:
          
          DISCLAIMER: This analysis is for informational purposes only and does not constitute legal advice.
        metadata:
          domain: "legal"
          requires_disclaimer: true
          citation_format: "bluebook"
      
      contract_review:
        template: |
          Contract Review:
          {context}
          
          Review Focus: {question}
          
          Contract Analysis:
          - Key Terms:
          - Potential Issues:
          - Recommendations:
          
          Note: This is a preliminary analysis only.
        metadata:
          domain: "legal"
          output_format: "structured_review"