name: "Medical Document Analysis Pipeline"
compliance:
  - "HIPAA"

rag_pipeline:
  retrieval_strategy: "metadata_filtered"
  retrieval_config:
    filters:
      document_type: "medical"
      privacy_level: "compliant"

prompts:
  strategy: "domain_specific"
  domain: "medical"
  config:
    compliance_mode: true
    pii_handling: "strict"
    
    templates:
      medical_qa:
        template: |
          Based on the medical documentation provided:
          {context}
          
          Medical Query: {question}
          
          IMPORTANT: This response is for informational purposes only and should not replace professional medical advice.
          
          Analysis:
        metadata:
          domain: "medical"
          compliance:
            - "HIPAA"
          disclaimer_required: true
      
      clinical_summary:
        template: |
          Summarize the following clinical information:
          {context}
          
          Provide a structured summary including:
          - Key findings
          - Relevant symptoms
          - Treatment considerations
          
          Note: This is a summary of provided information only.
        metadata:
          domain: "medical"
          output_format: "structured"