# Pinecone Store Component Schema
# JSON Schema draft-07 format
$schema: http://json-schema.org/draft-07/schema#
$id: components/stores/pinecone_store/schema.yaml
title: Pinecone Store Configuration
description: Pinecone vector database
type: object
additionalProperties: false
properties:
  api_key:
    type: string
    description: Pinecone API key
  environment:
    type: string
    default: us-east-1-aws
    description: Pinecone environment
  index_name:
    type: string
    pattern: ^[a-z0-9-]+$
    description: Index name
  dimension:
    type: integer
    minimum: 1
    maximum: 20000
    description: Vector dimension
  metric:
    type: string
    enum:
    - euclidean
    - cosine
    - dotproduct
    default: cosine
    description: Distance metric
required:
- api_key
- index_name
- dimension
