# Ollama Embedder Default Configurations

general_purpose:
  name: General Purpose
  description: Standard Ollama embeddings
  config:
    model: nomic-embed-text
    base_url: http://localhost:11434
    dimension: 768
    batch_size: 16
    timeout: 60
    auto_pull: true
  recommended_for:
  - Local deployment
  - Privacy-focused
  - Development
