name: hybrid_universal
type: retriever
class_name: HybridUniversal
description: HybridUniversal component
version: 1.0.0
dependencies:
  optional: []
  required: []
config_schema:
  type: object
  properties: {}
use_cases: []
