# Enterprise Data Processing RAG Configuration
# Uses the schema.yaml JSON Schema format
# Focus: Business data processing with structured and unstructured content

strategies:
  # ==============================================================================
  # CUSTOMER SUPPORT STRATEGY
  # ==============================================================================
  - name: "customer_support"
    description: "Process support tickets and knowledge base articles for intelligent assistance"
    tags: ["support", "tickets", "customer-service"]
    use_cases:
      - "Ticket routing and prioritization"
      - "Knowledge base search"
      - "Response suggestions"
      - "Issue pattern detection"
    
    components:
      parser:
        type: "CSVParser"
        config:
          content_fields: ["subject", "description", "resolution", "notes"]
          metadata_fields: ["ticket_id", "priority", "category", "status", "created_date", "resolved_date", "agent"]
          id_field: "ticket_id"
          combine_content: true
          content_separator: "\n\n"
          encoding: "utf-8"
      
      extractors:
        - type: "EntityExtractor"
          priority: 95
          config:
            entity_types: ["PERSON", "ORG", "EMAIL", "PHONE", "URL"]
            use_fallback: true
            min_entity_length: 3
            merge_entities: true
        
        - type: "DateTimeExtractor"
          priority: 90
          config:
            fuzzy_parsing: true
            extract_relative: true
            extract_durations: true
            default_timezone: "UTC"
            prefer_dates_from: "past"
        
        - type: "KeywordExtractor"
          priority: 80
          config:
            algorithm: "rake"
            max_keywords: 15
            min_keyword_length: 4
            include_scores: true
        
        - type: "StatisticsExtractor"
          priority: 70
          config:
            include_readability: false
            include_vocabulary: true
            include_sentiment: true
            include_language: true
      
      embedder:
        type: "OllamaEmbedder"
        config:
          model: "nomic-embed-text"
          base_url: "http://localhost:11434"
          dimension: 768
          batch_size: 32
          timeout: 120
          auto_pull: true
      
      vector_store:
        type: "ChromaStore"
        config:
          collection_name: "support_tickets"
          persist_directory: "./vectordb/support"
          distance_function: "cosine"
      
      retrieval_strategy:
        type: "MetadataFilteredStrategy"
        config:
          top_k: 25
          filters:
            priority: ["high", "critical"]
            status: ["resolved"]
          filter_mode: "pre"
          fallback_multiplier: 2

  # ==============================================================================
  # FINANCIAL REPORTS STRATEGY
  # ==============================================================================
  - name: "financial_reports"
    description: "Process financial documents including spreadsheets and quarterly reports"
    tags: ["finance", "analytics", "reporting"]
    use_cases:
      - "Financial analysis"
      - "Quarterly reporting"
      - "Budget tracking"
      - "Performance metrics"
    
    components:
      parser:
        type: "ExcelParser"
        config:
          sheet_names: null  # Process all sheets
          combine_sheets: false
          extract_formulas: true
          extract_charts: true
          table_format: "markdown"
          header_row: 0
      
      extractors:
        - type: "TableExtractor"
          priority: 100
          config:
            output_format: "dict"
            extract_headers: true
            merge_cells: true
            min_rows: 3
        
        - type: "StatisticsExtractor"
          priority: 90
          config:
            include_readability: false
            include_vocabulary: false
            include_structure: true
            include_sentiment: false
            include_language: false
        
        - type: "PatternExtractor"
          priority: 85
          config:
            predefined_patterns: []
            custom_patterns:
              - name: "currency_amount"
                pattern: "\\$[0-9]{1,3}(?:,[0-9]{3})*(?:\\.[0-9]{2})?"
                description: "USD currency amounts"
              - name: "percentage"
                pattern: "\\b\\d{1,3}(?:\\.\\d{1,2})?%"
                description: "Percentage values"
              - name: "quarter_year"
                pattern: "Q[1-4]\\s*20\\d{2}"
                description: "Quarter and year"
            return_positions: true
        
        - type: "DateTimeExtractor"
          priority: 80
          config:
            fuzzy_parsing: false
            extract_relative: false
            date_format: "ISO"
            prefer_dates_from: "current"
      
      embedder:
        type: "HuggingFaceEmbedder"
        config:
          model_name: "sentence-transformers/all-MiniLM-L6-v2"
          device: "auto"
          batch_size: 48
          normalize_embeddings: true
          show_progress_bar: false
      
      vector_store:
        type: "QdrantStore"
        config:
          host: "localhost"
          port: 6333
          collection_name: "financial_reports"
          vector_size: 384
          distance: "Cosine"
          on_disk: false
      
      retrieval_strategy:
        type: "RerankedStrategy"
        config:
          initial_k: 40
          final_k: 10
          rerank_factors:
            similarity_weight: 0.5
            recency_weight: 0.3
            length_weight: 0.1
            metadata_weight: 0.1
          normalize_scores: true

  # ==============================================================================
  # BUSINESS EMAILS STRATEGY
  # ==============================================================================
  - name: "business_emails"
    description: "Process and analyze business email communications"
    tags: ["email", "communication", "archive"]
    use_cases:
      - "Email search and retrieval"
      - "Communication analysis"
      - "Contact extraction"
      - "Thread reconstruction"
    
    components:
      parser:
        type: "HTMLParser"
        config:
          extract_metadata: true
          extract_links: true
          extract_images: false
          preserve_structure: false
          remove_scripts: true
          remove_styles: true
          text_only: false
      
      extractors:
        - type: "LinkExtractor"
          priority: 95
          config:
            extract_urls: true
            extract_emails: true
            extract_domains: true
            validate_urls: false
            resolve_redirects: false
        
        - type: "EntityExtractor"
          priority: 90
          config:
            entity_types: ["PERSON", "ORG", "EMAIL", "PHONE"]
            use_fallback: true
            confidence_threshold: 0.6
        
        - type: "SummaryExtractor"
          priority: 75
          config:
            summary_sentences: 3
            algorithm: "lsa"
            include_key_phrases: true
            include_statistics: false
      
      embedder:
        type: "SentenceTransformerEmbedder"
        config:
          model_name: "all-MiniLM-L6-v2"
          device: "cpu"
          batch_size: 32
          normalize_embeddings: true
          pooling_strategy: "mean"
      
      vector_store:
        type: "ChromaStore"
        config:
          collection_name: "business_emails"
          persist_directory: "./vectordb/emails"
          distance_function: "cosine"
      
      retrieval_strategy:
        type: "MultiQueryStrategy"
        config:
          num_queries: 4
          top_k: 15
          aggregation_method: "reciprocal_rank"
          query_weights: null

  # ==============================================================================
  # HR DOCUMENTS STRATEGY
  # ==============================================================================
  - name: "hr_documents"
    description: "Process HR documents including policies, procedures, and employee records"
    tags: ["hr", "policies", "compliance", "confidential"]
    use_cases:
      - "Policy search"
      - "Compliance verification"
      - "Employee handbook queries"
      - "Procedure documentation"
    
    components:
      parser:
        type: "DocxParser"
        config:
          extract_metadata: true
          extract_headers_footers: true
          extract_comments: true
          extract_tables: true
          extract_images: false
          preserve_formatting: false
      
      extractors:
        - type: "HeadingExtractor"
          priority: 95
          config:
            max_level: 4
            include_hierarchy: true
            extract_outline: true
            min_heading_length: 3
        
        - type: "PatternExtractor"
          priority: 90
          config:
            predefined_patterns: ["ssn", "phone", "email"]
            custom_patterns:
              - name: "employee_id"
                pattern: "EMP\\d{6}"
                description: "Employee ID"
              - name: "policy_code"
                pattern: "POL-[A-Z]{2,4}-\\d{3}"
                description: "Policy identifier"
            case_sensitive: true
        
        - type: "KeywordExtractor"
          priority: 80
          config:
            algorithm: "tfidf"
            max_keywords: 25
            min_keyword_length: 4
            language: "english"
      
      embedder:
        type: "OllamaEmbedder"
        config:
          model: "mxbai-embed-large"
          base_url: "http://localhost:11434"
          dimension: 1024
          batch_size: 16
          timeout: 90
      
      vector_store:
        type: "FAISSStore"
        config:
          dimension: 1024
          index_type: "Flat"
          metric: "L2"
          use_gpu: false
      
      retrieval_strategy:
        type: "HybridUniversalStrategy"
        config:
          strategies:
            - type: "MetadataFilteredStrategy"
              weight: 0.6
              config:
                top_k: 20
                filter_mode: "pre"
            
            - type: "BasicSimilarityStrategy"
              weight: 0.4
              config:
                top_k: 30
                distance_metric: "euclidean"
                score_threshold: 0.7
          
          combination_method: "rank_fusion"
          final_k: 12

# ==============================================================================
# COMPONENT METADATA
# ==============================================================================
component_metadata:
  parsers:
    CSVParser:
      description: "Optimized for structured tabular data"
      class_name: "CSVParser"
      module: "components.parsers.csv_parser"
      use_cases: ["support tickets", "sales data", "inventory"]
      dependencies:
        required: []
        optional: ["pandas"]
    
    ExcelParser:
      description: "Handles complex spreadsheets with multiple sheets"
      class_name: "ExcelParser"
      module: "components.parsers.excel_parser"
      use_cases: ["financial reports", "analytics", "budgets"]
      dependencies:
        required: ["openpyxl"]
        optional: ["pandas", "xlrd"]
    
    DocxParser:
      description: "Microsoft Word document processing"
      class_name: "DocxParser"
      module: "components.parsers.docx_parser"
      use_cases: ["policies", "contracts", "reports"]
      dependencies:
        required: ["python-docx"]
        optional: ["docx2txt"]
    
    HTMLParser:
      description: "Web content and email processing"
      class_name: "HTMLParser"
      module: "components.parsers.html_parser"
      use_cases: ["emails", "web pages", "archives"]
      dependencies:
        required: ["beautifulsoup4"]
        optional: ["lxml", "html5lib"]

# ==============================================================================
# BEST PRACTICES
# ==============================================================================
best_practices:
  enterprise_data:
    - "Use metadata filtering for business-critical searches"
    - "Enable PII detection for compliance-sensitive documents"
    - "Implement role-based access through namespace isolation"
    - "Use hybrid strategies for balanced precision and recall"
    - "Cache embeddings for frequently accessed documents"
  
  performance_optimization:
    - "Batch process similar document types together"
    - "Use appropriate chunk sizes based on content density"
    - "Enable GPU acceleration for large-scale processing"
    - "Implement incremental indexing for growing datasets"
  
  security_compliance:
    - "Encrypt vector stores containing sensitive data"
    - "Use local embedders for confidential documents"
    - "Implement audit logging for all searches"
    - "Regular PII scans and redaction processes"