name: sentence_transformer_embedder
type: embedder
class_name: SentenceTransformerEmbedder
description: SentenceTransformerEmbedder component
version: 1.0.0
dependencies:
  optional: []
  required: []
config_schema:
  type: object
  properties: {}
use_cases: []
