from core.logging import FastAPIStructLogger

from atomic_agents.agents.base_agent import BaseAgent
from atomic_agents.lib.components.chat_history import ChatHistory
from atomic_agents.lib.components.system_prompt_generator import SystemPromptGenerator
from atomic_agents.agents.atomic_agent import (
    AtomicAgent,
)
from pydantic import BaseModel, Field
import instructor
from openai import AsyncOpenAI

from services.settings import get_settings
from config.datamodel import Prompt, LlamaFarmConfig, Provider

settings = get_settings()
logger = FastAPIStructLogger()


class ProjectChatOrchestratorAgentInputSchema(BaseModel):
    """Input schema for the agent. Contains the chat message from the user."""

    chat_message: str = Field(
        ...,
        description=(
            "The chat message from the user. "
            "This is the message that the user has typed into the chat interface."
        ),
    )


class ProjectChatOrchestratorAgentOutputSchema(BaseModel):
    """Output schema for the agent. Contains the markdown-enabled response generated by the chat agent."""

    chat_message: str = Field(
        ...,
        description=(
            "The chat message exchanged between the user and the chat agent. "
            "This contains the markdown-enabled response generated by the chat agent."
        ),
    )


class BasicChatOutputSchema(BaseModel):
    """Basic output schema for streaming chat responses."""

    chat_message: str = Field(
        ...,
        description=(
            "The chat message exchanged between the user and the chat agent. "
            "This contains the markdown-enabled response generated by the chat agent."
        ),
    )


class PartialBasicChatOutputSchema(BaseModel):
    """Partial output schema for streaming chat responses."""

    chat_message: str = Field(
        ...,
        description=(
            "The chat message exchanged between the user and the chat agent. "
            "This contains the markdown-enabled response generated by the chat agent."
        ),
    )


class ProjectChatOrchestratorAgent(
    AtomicAgent[
        ProjectChatOrchestratorAgentInputSchema,
        ProjectChatOrchestratorAgentOutputSchema,
    ]
):
    pass


def _get_system_prompt(project_config: LlamaFarmConfig) -> str:
    """Extract the system prompt from the project configuration."""
    for prompt in project_config.prompts or []:
        if prompt.role == "system":
            return prompt.content
    return "You are a helpful assistant."


def _prompt_to_content_schema(
    prompt: Prompt,
) -> ProjectChatOrchestratorAgentOutputSchema | ProjectChatOrchestratorAgentInputSchema:
    """Convert a prompt to a content schema for the chat history."""
    if prompt.role == "assistant":
        return ProjectChatOrchestratorAgentOutputSchema(
            chat_message=prompt.content,
        )
    elif prompt.role == "user":
        return ProjectChatOrchestratorAgentInputSchema(
            chat_message=prompt.content,
        )
    else:
        raise ValueError(f"Unsupported role: {prompt.role}")


def _populate_history_with_non_system_prompts(
    history: ChatHistory, project_config: LlamaFarmConfig
):
    for prompt in project_config.prompts or []:
        # Only add non-system prompts to the history
        if prompt.role != "system":
            history.add_message(
                role=prompt.role,
                content=_prompt_to_content_schema(prompt),
            )


def _get_history(project_config: LlamaFarmConfig) -> ChatHistory:
    history = ChatHistory()
    _populate_history_with_non_system_prompts(history, project_config)
    return history


def _get_instructor_mode(project_config: LlamaFarmConfig) -> instructor.Mode:
    """Determine the instructor mode based on configuration and provider."""
    
    # Check if instructor_mode is configured
    if project_config.runtime.instructor_mode is not None:
        # Handle enum type - get the string value
        mode_str = project_config.runtime.instructor_mode.value
        
        try:
            mode = instructor.mode.Mode[mode_str.upper()]
            logger.info(f"Using configured instructor mode: {mode}")
            return mode
        except (KeyError, AttributeError):
            logger.warning(f"Invalid instructor mode '{mode_str}', falling back to provider default")
    
    # Default based on provider
    if project_config.runtime.provider == Provider.ollama:
        mode = instructor.Mode.MD_JSON
        logger.info("Using MD_JSON mode for Ollama provider (default)")
    else:
        mode = instructor.Mode.TOOLS
        logger.info("Using TOOLS mode as default")
    
    return mode


def _get_max_retries(project_config: LlamaFarmConfig) -> int:
    """Get the max retries configuration."""
    # Check if max_retries is in model_api_parameters
    if project_config.runtime.model_api_parameters:
        max_retries = project_config.runtime.model_api_parameters.get("max_retries")
        if max_retries is not None:
            return int(max_retries)
    
    # Default based on provider
    if project_config.runtime.provider == Provider.ollama:
        return 3  # Ollama needs more retries for parsing issues
    return 2  # Default for other providers


def _get_client(project_config: LlamaFarmConfig) -> instructor.client.Instructor:
    """Create an instructor client based on project configuration."""
    
    # Get the instructor mode
    mode = _get_instructor_mode(project_config)
    
    # Get max retries
    max_retries = _get_max_retries(project_config)
    
    logger.info(f"Creating instructor client with mode={mode}, max_retries={max_retries}")
    
    # Create the base OpenAI client
    if project_config.runtime.provider == Provider.openai:
        base_client = AsyncOpenAI(
            api_key=project_config.runtime.api_key,
            base_url=project_config.runtime.base_url,
        )
    elif project_config.runtime.provider == Provider.ollama:
        base_client = AsyncOpenAI(
            api_key=project_config.runtime.api_key or settings.ollama_api_key,
            base_url=project_config.runtime.base_url or f"{settings.ollama_host}/v1",
        )
    else:
        raise ValueError(f"Unsupported provider: {project_config.runtime.provider}")
    
    # Create instructor client
    client = instructor.from_openai(base_client, mode=mode)
    client.max_retries = max_retries
    
    return client


def get_project_chat_orchestrator_agent(
    project_config: LlamaFarmConfig,
) -> BaseAgent:
    """Create a project chat orchestrator agent for the given project configuration."""
    system_prompt = _get_system_prompt(project_config)
    history = _get_history(project_config)
    client = _get_client(project_config)

    return ProjectChatOrchestratorAgent(
        client=client,
        model=project_config.runtime.model,
        system_prompt_generator=SystemPromptGenerator(
            background=[system_prompt],
            steps=[],
        ),
        input_schema=ProjectChatOrchestratorAgentInputSchema,
        output_schema=BasicChatOutputSchema,
        memory=history,
    )