# Legal and Finance RAG Strategies
# Compliance-focused configurations for legal and financial document processing
# Covers: Contracts, regulations, financial reports, audit trails, risk management

# ============================================================================
# LEGAL CONTRACT ANALYSIS STRATEGY
# ============================================================================
legal_contract_analysis:
  description: "Comprehensive contract analysis with clause extraction and risk identification"
  use_cases:
    - "Contract review and analysis"
    - "Clause comparison"
    - "Risk assessment"
    - "Compliance verification"
  
  components:
    parser:
      type: "LegalDocumentParser"
      config:
        formats: ["pdf", "docx", "txt"]
        extract_metadata: true        # Parties, dates, signatures
        preserve_formatting: true      # Legal formatting matters
        extract_headers_footers: true  # Page numbers, references
        chunk_strategy: "clause"       # Chunk by clause/section
        chunk_size: 512               # Smaller for precise retrieval
        chunk_overlap: 100
        # Compliance: Maintain document integrity
        hash_original: true           # Hash for tamper detection
    
    extractors:
      # Legal entity extraction
      - type: "LegalEntityExtractor"
        config:
          entities:
            - "PARTY"                 # Contracting parties
            - "JURISDICTION"          # Legal jurisdictions
            - "COURT"                 # Court references
            - "STATUTE"               # Legal statutes
            - "CASE_LAW"              # Case citations
          party_role_detection: true   # Identify party roles
          signatory_extraction: true   # Extract signatories
      
      # Clause identification and extraction
      - type: "ClauseExtractor"
        config:
          clause_types:
            - "indemnification"
            - "limitation_of_liability"
            - "termination"
            - "confidentiality"
            - "non_compete"
            - "payment_terms"
            - "warranty"
            - "force_majeure"
            - "dispute_resolution"
            - "governing_law"
          extract_full_text: true
          identify_modifications: true  # Track amendments
          flag_unusual_terms: true     # Identify non-standard clauses
      
      # Date and deadline extraction
      - type: "LegalDateExtractor"
        config:
          date_types:
            - "effective_date"
            - "expiration_date"
            - "notice_period"
            - "renewal_date"
            - "payment_due"
          calculate_deadlines: true     # Calculate important dates
          timezone_aware: true
          working_days_calculation: true
      
      # Financial terms extraction
      - type: "FinancialTermsExtractor"
        config:
          extract_amounts: true
          extract_payment_schedules: true
          extract_penalties: true
          extract_interest_rates: true
          currency_normalization: true
          calculate_total_value: true
      
      # Risk assessment
      - type: "LegalRiskExtractor"
        config:
          risk_categories:
            - "financial"
            - "operational"
            - "compliance"
            - "reputational"
          risk_indicators:
            - "unlimited_liability"
            - "auto_renewal"
            - "unilateral_termination"
            - "broad_indemnification"
          calculate_risk_score: true
          threshold_alerts: true
    
    embedder:
      type: "LegalBertEmbedder"       # Legal-specific embeddings
      config:
        model: "nlpaueb/legal-bert-base-uncased"
        dimension: 768
        batch_size: 16
        max_length: 512
        # Security: Local processing only
        local_only: true
    
    vector_store:
      type: "SecureVectorStore"
      config:
        backend: "chromadb"
        collection_name: "legal_contracts"
        persist_directory: "./vectordb/legal/contracts"
        # Security and compliance
        encryption: "AES-256-GCM"
        access_control: true
        audit_logging: true
        version_control: true          # Track document versions
        metadata_config:
          indexed_fields: ["contract_type", "party", "effective_date", "jurisdiction"]
          encrypted_fields: ["party_details", "financial_terms"]
    
    retrieval_strategy:
      type: "LegalRetrievalStrategy"
      config:
        top_k: 10
        similarity_threshold: 0.75     # Higher threshold for accuracy
        clause_matching: true          # Match specific clauses
        precedent_search: true         # Find similar contracts
        cross_reference: true          # Link related documents

# ============================================================================
# FINANCIAL REPORTING STRATEGY
# ============================================================================
financial_reporting_analysis:
  description: "Analysis of financial statements, reports, and regulatory filings"
  use_cases:
    - "Financial statement analysis"
    - "Earnings report processing"
    - "Regulatory filing review"
    - "Trend analysis"
  
  components:
    parser:
      type: "FinancialDocumentParser"
      config:
        formats: ["pdf", "xlsx", "xbrl", "html"]
        extract_tables: true           # Financial tables critical
        table_structure_preservation: true
        extract_charts: true           # Financial charts
        number_formatting: true        # Preserve number formats
        chunk_strategy: "section"      # By financial statement section
        chunk_size: 768
        chunk_overlap: 150
    
    extractors:
      # Financial metrics extraction
      - type: "FinancialMetricsExtractor"
        config:
          metrics:
            # Income statement
            - "revenue"
            - "gross_profit"
            - "operating_income"
            - "net_income"
            - "ebitda"
            - "eps"
            # Balance sheet
            - "total_assets"
            - "total_liabilities"
            - "shareholders_equity"
            - "working_capital"
            # Cash flow
            - "operating_cash_flow"
            - "free_cash_flow"
            # Ratios
            - "pe_ratio"
            - "debt_to_equity"
            - "current_ratio"
            - "roa"
            - "roe"
          period_detection: true        # Q1, Q2, FY, YTD
          year_over_year: true         # YoY comparisons
          quarter_over_quarter: true   # QoQ comparisons
      
      # XBRL tag extraction
      - type: "XBRLExtractor"
        config:
          taxonomies: ["US-GAAP", "IFRS"]
          extract_contexts: true
          extract_dimensions: true
          validate_calculations: true
          map_to_standard: true        # Map to standard metrics
      
      # Table extraction and analysis
      - type: "FinancialTableExtractor"
        config:
          identify_statement_type: true # Income, balance, cash flow
          extract_line_items: true
          preserve_hierarchy: true      # Account hierarchy
          extract_totals: true
          validate_arithmetic: true     # Check calculations
      
      # Regulatory compliance extraction
      - type: "RegulatoryExtractor"
        config:
          filing_types: ["10-K", "10-Q", "8-K", "DEF 14A"]
          extract_risk_factors: true
          extract_md_and_a: true        # MD&A section
          extract_controls: true        # Internal controls
          sox_compliance: true          # SOX requirements
      
      # Audit findings extraction
      - type: "AuditExtractor"
        config:
          extract_auditor_opinion: true
          identify_going_concern: true
          extract_critical_matters: true
          extract_restatements: true
          identify_weaknesses: true
    
    embedder:
      type: "FinancialEmbedder"
      config:
        model: "yiyanghkust/finbert-pretrain"
        dimension: 768
        batch_size: 24
        numerical_encoding: true       # Encode numbers specially
    
    vector_store:
      type: "FinancialVectorStore"
      config:
        backend: "qdrant"
        collection_name: "financial_reports"
        persist_directory: "./vectordb/finance/reports"
        # Compliance features
        sox_compliant: true
        immutable_storage: true        # Write-once for compliance
        retention_policy: "7_years"
        metadata_config:
          indexed_fields: ["company", "filing_type", "fiscal_period", "fiscal_year"]
          numerical_fields: ["revenue", "net_income", "total_assets"]
    
    retrieval_strategy:
      type: "FinancialAnalysisStrategy"
      config:
        top_k: 15
        time_series_aware: true        # Consider temporal relationships
        peer_comparison: true          # Compare with peer companies
        metric_aggregation: true       # Aggregate financial metrics

# ============================================================================
# REGULATORY COMPLIANCE STRATEGY
# ============================================================================
regulatory_compliance_monitoring:
  description: "Monitor and analyze regulatory requirements and compliance status"
  use_cases:
    - "Regulatory change tracking"
    - "Compliance gap analysis"
    - "Policy mapping"
    - "Audit preparation"
  
  components:
    parser:
      type: "RegulatoryDocumentParser"
      config:
        formats: ["pdf", "html", "xml"]
        extract_structure: true        # Regulatory structure
        extract_definitions: true      # Legal definitions
        extract_requirements: true     # Compliance requirements
        extract_penalties: true        # Non-compliance penalties
        chunk_strategy: "requirement"  # Chunk by requirement
        chunk_size: 512
        preserve_numbering: true       # Section numbers critical
    
    extractors:
      # Regulatory requirement extraction
      - type: "RequirementExtractor"
        config:
          requirement_types:
            - "mandatory"             # Must comply
            - "recommended"           # Should comply
            - "optional"              # May comply
          extract_conditions: true     # If-then conditions
          extract_exceptions: true     # Exemptions
          extract_timelines: true      # Compliance deadlines
          extract_scope: true          # Who it applies to
      
      # Regulation reference extraction
      - type: "RegulationReferenceExtractor"
        config:
          regulations:
            - "GDPR"
            - "CCPA"
            - "HIPAA"
            - "SOX"
            - "FCRA"
            - "Basel III"
            - "MiFID II"
            - "Dodd-Frank"
          extract_articles: true       # Article references
          extract_sections: true       # Section references
          cross_reference: true        # Links between regulations
      
      # Penalty and enforcement extraction
      - type: "EnforcementExtractor"
        config:
          extract_penalties: true
          penalty_types:
            - "monetary"
            - "criminal"
            - "administrative"
            - "reputational"
          extract_enforcement_actions: true
          extract_precedents: true
      
      # Compliance mapping
      - type: "ComplianceMappingExtractor"
        config:
          map_to_controls: true        # Map to internal controls
          map_to_policies: true        # Map to company policies
          identify_gaps: true          # Compliance gaps
          calculate_coverage: true     # Compliance coverage %
    
    embedder:
      type: "RegulatoryEmbedder"
      config:
        model: "nlpaueb/legal-bert-base-uncased"
        dimension: 768
        batch_size: 16
        domain_adaptation: true        # Adapted for regulations
    
    vector_store:
      type: "ComplianceVectorStore"
      config:
        backend: "chromadb"
        collection_name: "regulatory_compliance"
        persist_directory: "./vectordb/compliance/regulations"
        # Compliance features
        change_tracking: true          # Track regulation changes
        version_history: true          # Maintain all versions
        metadata_config:
          indexed_fields: ["regulation", "jurisdiction", "effective_date", "industry"]
    
    retrieval_strategy:
      type: "ComplianceStrategy"
      config:
        top_k: 20
        jurisdiction_filtering: true   # Filter by jurisdiction
        industry_filtering: true       # Filter by industry
        temporal_filtering: true       # Currently effective
        include_upcoming: true         # Upcoming requirements

# ============================================================================
# RISK MANAGEMENT STRATEGY
# ============================================================================
enterprise_risk_management:
  description: "Comprehensive risk identification, assessment, and monitoring"
  use_cases:
    - "Risk assessment"
    - "Risk reporting"
    - "Incident analysis"
    - "Mitigation planning"
  
  components:
    parser:
      type: "RiskDocumentParser"
      config:
        formats: ["pdf", "docx", "xlsx", "csv"]
        extract_risk_matrices: true    # Risk assessment matrices
        extract_heat_maps: true        # Risk heat maps
        extract_workflows: true        # Risk workflows
        chunk_size: 768
        chunk_overlap: 150
    
    extractors:
      # Risk identification
      - type: "RiskIdentificationExtractor"
        config:
          risk_categories:
            - "operational"
            - "financial"
            - "strategic"
            - "compliance"
            - "reputational"
            - "cyber"
            - "market"
            - "credit"
          risk_sources: true           # Identify risk sources
          risk_triggers: true          # Identify triggers
          emerging_risks: true         # Flag new risks
      
      # Risk assessment extraction
      - type: "RiskAssessmentExtractor"
        config:
          extract_probability: true
          extract_impact: true
          extract_velocity: true       # Speed of onset
          calculate_risk_score: true
          risk_appetite: true          # Compare to appetite
          residual_risk: true          # After controls
      
      # Control extraction
      - type: "ControlExtractor"
        config:
          control_types:
            - "preventive"
            - "detective"
            - "corrective"
            - "compensating"
          control_effectiveness: true
          control_gaps: true
          testing_frequency: true
      
      # Incident extraction
      - type: "IncidentExtractor"
        config:
          extract_root_cause: true
          extract_impact: true
          extract_response: true
          extract_lessons_learned: true
          link_to_risks: true          # Link incidents to risks
    
    embedder:
      type: "RiskEmbedder"
      config:
        model: "sentence-transformers/all-mpnet-base-v2"
        dimension: 768
        batch_size: 24
        risk_weighting: true           # Weight by risk score
    
    vector_store:
      type: "RiskVectorStore"
      config:
        backend: "qdrant"
        collection_name: "risk_management"
        persist_directory: "./vectordb/risk/assessments"
        metadata_config:
          indexed_fields: ["risk_category", "risk_level", "business_unit", "assessment_date"]
          sortable_fields: ["risk_score", "residual_risk"]
    
    retrieval_strategy:
      type: "RiskPrioritizationStrategy"
      config:
        top_k: 15
        prioritize_by: "risk_score"    # Sort by risk
        include_related: true          # Related risks
        include_controls: true         # Associated controls
        trend_analysis: true           # Risk trends over time

# ============================================================================
# AUDIT TRAIL STRATEGY
# ============================================================================
audit_trail_analysis:
  description: "Comprehensive audit trail processing and anomaly detection"
  use_cases:
    - "Audit log analysis"
    - "Compliance verification"
    - "Fraud detection"
    - "Access review"
  
  components:
    parser:
      type: "AuditLogParser"
      config:
        formats: ["json", "csv", "syslog", "xml"]
        timestamp_parsing: true        # Parse all timestamp formats
        user_extraction: true          # Extract user information
        action_extraction: true        # Extract actions
        resource_extraction: true      # Extract affected resources
        chunk_strategy: "time_window"  # Chunk by time
        time_window: "1hour"
    
    extractors:
      # Audit event extraction
      - type: "AuditEventExtractor"
        config:
          event_types:
            - "authentication"
            - "authorization"
            - "data_access"
            - "data_modification"
            - "configuration_change"
            - "privilege_escalation"
          extract_outcome: true         # Success/failure
          extract_reason: true          # Reason for action
          extract_ip_address: true
          extract_location: true
      
      # Anomaly detection
      - type: "AnomalyExtractor"
        config:
          anomaly_types:
            - "unusual_time"           # Outside business hours
            - "unusual_location"       # Unexpected location
            - "unusual_volume"         # High volume of actions
            - "unusual_pattern"        # Behavioral anomaly
            - "failed_attempts"        # Multiple failures
          baseline_learning: true      # Learn normal patterns
          threshold_based: true
          ml_based: true               # ML anomaly detection
      
      # Compliance verification
      - type: "ComplianceAuditExtractor"
        config:
          verify_segregation: true     # Segregation of duties
          verify_approval: true        # Approval workflows
          verify_retention: true       # Data retention
          verify_access: true          # Access controls
          flag_violations: true
      
      # Chain of custody
      - type: "ChainOfCustodyExtractor"
        config:
          track_data_lineage: true
          track_approvals: true
          track_modifications: true
          cryptographic_validation: true
    
    embedder:
      type: "AuditEmbedder"
      config:
        model: "sentence-transformers/all-MiniLM-L6-v2"
        dimension: 384                # Smaller for high volume
        batch_size: 128               # Large batches for logs
        temporal_encoding: true        # Encode time information
    
    vector_store:
      type: "AuditVectorStore"
      config:
        backend: "chromadb"
        collection_name: "audit_trails"
        persist_directory: "./vectordb/audit/logs"
        # Audit-specific features
        immutable: true               # Cannot modify logs
        timestamped: true             # All entries timestamped
        cryptographic_proof: true     # Hash chain for integrity
        metadata_config:
          indexed_fields: ["user", "action", "resource", "timestamp", "outcome"]
          time_based_partitioning: true
    
    retrieval_strategy:
      type: "AuditInvestigationStrategy"
      config:
        top_k: 50                     # More results for investigation
        temporal_correlation: true     # Find related events in time
        user_behavior_analysis: true   # Analyze user patterns
        forensic_timeline: true        # Build timeline of events