# Medical Assistant RAG Strategies
# HIPAA-compliant configuration for healthcare documentation and clinical decision support
# Covers: Clinical notes, medical literature, drug information, patient education

# ============================================================================
# CLINICAL NOTES STRATEGY
# ============================================================================
clinical_notes_ehr:
  description: "Process and search electronic health records, clinical notes, and patient documentation"
  use_cases:
    - "Patient history review"
    - "Clinical decision support"
    - "Care continuity"
    - "Quality metrics extraction"
  
  components:
    parser:
      type: "TextParser"
      config:
        encoding: "utf-8"
        chunk_size: 512               # Balance context with precision
        chunk_overlap: 100            # Maintain clinical context
        preserve_formatting: true      # Maintain note structure
        # HIPAA Compliance: No data leaves local system
        local_only: true
    
    extractors:
      # Medical entity extraction with privacy
      - type: "MedicalEntityExtractor"  # Specialized medical NER
        config:
          entities:
            - "CONDITION"             # Diseases, symptoms
            - "MEDICATION"            # Drug names, dosages
            - "PROCEDURE"             # Medical procedures
            - "ANATOMY"               # Body parts, systems
            - "LAB_VALUE"             # Test results
          model: "en_core_sci_md"     # ScispaCy medical model
          anonymize_phi: true         # Remove patient identifiers
          phi_types:                  # HIPAA identifiers
            - "NAME"
            - "SSN"
            - "MRN"                   # Medical Record Number
            - "DOB"
            - "ADDRESS"
            - "PHONE"
      
      # ICD-10 and CPT code extraction
      - type: "PatternExtractor"
        config:
          patterns:
            icd10: "[A-Z]\\d{2}\\.?\\d{0,4}"     # ICD-10 diagnosis codes
            cpt: "\\d{5}"                         # CPT procedure codes
            loinc: "\\d{1,5}-\\d"                 # LOINC lab codes
            ndc: "\\d{5}-\\d{4}-\\d{2}"          # NDC drug codes
            vitals: "BP:\\s*\\d{2,3}/\\d{2,3}"    # Blood pressure
          include_context: true
          context_window: 50
      
      # Clinical summary generation
      - type: "ClinicalSummaryExtractor"  # Custom medical summarizer
        config:
          sections:
            - "chief_complaint"
            - "history_present_illness"
            - "assessment"
            - "plan"
          max_length: 200
          include_diagnoses: true
          include_medications: true
      
      # Temporal information extraction
      - type: "MedicalTimelineExtractor"
        config:
          extract_onset: true         # Symptom onset
          extract_duration: true      # Condition duration
          extract_frequency: true     # Medication frequency
          temporal_relations: true    # Before/after relationships
    
    embedder:
      type: "BioBertEmbedder"         # Medical-specific embeddings
      config:
        model: "dmis-lab/biobert-base-cased-v1.2"
        dimension: 768
        batch_size: 16
        max_length: 512
        # HIPAA: Local embeddings only
        local_only: true
    
    vector_store:
      type: "ChromaStore"
      config:
        collection_name: "clinical_notes"
        persist_directory: "./vectordb/medical/clinical"
        # HIPAA: Encryption at rest
        encryption: "AES-256"
        access_control: true
        metadata_config:
          indexed_fields: ["encounter_date", "provider", "department"]
          # PHI fields are hashed, not stored directly
          hashed_fields: ["patient_id", "mrn"]
    
    retrieval_strategy:
      type: "MetadataFilteredStrategy"
      config:
        top_k: 10
        # Filter by date for relevant history
        filters:
          date_range: "configurable"   # Last 6 months, 1 year, etc.
          department: "configurable"   # Cardiology, Oncology, etc.
        filter_mode: "pre"
        # Additional privacy filtering
        privacy_filter: true           # Ensure user has access rights

# ============================================================================
# MEDICAL LITERATURE STRATEGY
# ============================================================================
medical_literature_research:
  description: "Search medical journals, clinical guidelines, and research papers"
  use_cases:
    - "Evidence-based medicine"
    - "Clinical guideline lookup"
    - "Drug interaction checking"
    - "Treatment protocol verification"
  
  components:
    parser:
      type: "PDFParser"
      config:
        extract_images: false         # Usually not needed for literature
        extract_tables: true          # Clinical trial data
        extract_metadata: true        # Publication info
        chunk_size: 1024              # Larger for academic context
        chunk_overlap: 200
    
    extractors:
      # Citation and evidence extraction
      - type: "CitationExtractor"
        config:
          formats: ["APA", "AMA", "Vancouver"]  # Medical citation styles
          extract_doi: true
          extract_pmid: true           # PubMed ID
          validate: true
      
      # Clinical evidence level
      - type: "EvidenceLevelExtractor"
        config:
          classification:
            - "Level I"               # Systematic reviews, meta-analyses
            - "Level II"              # RCTs
            - "Level III"             # Cohort studies
            - "Level IV"              # Case-control studies
            - "Level V"               # Case reports
          extract_study_design: true
          extract_sample_size: true
          extract_p_values: true
      
      # Medical statistics extraction
      - type: "StatisticalExtractor"
        config:
          metrics:
            - "p_value"
            - "confidence_interval"
            - "odds_ratio"
            - "relative_risk"
            - "number_needed_to_treat"
          extract_context: true
      
      # Key findings summarization
      - type: "AbstractExtractor"
        config:
          sections:
            - "background"
            - "methods" 
            - "results"
            - "conclusions"
          max_length: 300
    
    embedder:
      type: "PubMedBertEmbedder"      # Trained on medical literature
      config:
        model: "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract"
        dimension: 768
        batch_size: 24
    
    vector_store:
      type: "ChromaStore"
      config:
        collection_name: "medical_literature"
        persist_directory: "./vectordb/medical/literature"
        metadata_config:
          indexed_fields: ["publication_year", "journal", "evidence_level"]
    
    retrieval_strategy:
      type: "RerankedStrategy"
      config:
        initial_k: 30
        final_k: 5
        rerank_factors:
          recency_weight: 0.4         # Prefer recent studies
          relevance_weight: 0.4
          metadata_boost:
            evidence_level:
              "Level I": 2.0          # Highest quality evidence
              "Level II": 1.5
              "Level III": 1.2
              "Level IV": 1.0
              "Level V": 0.8

# ============================================================================
# DRUG INFORMATION STRATEGY
# ============================================================================
drug_information_formulary:
  description: "Comprehensive drug information, interactions, and formulary management"
  use_cases:
    - "Drug interaction checking"
    - "Dosing guidelines"
    - "Contraindication alerts"
    - "Formulary alternatives"
  
  components:
    parser:
      type: "StructuredDataParser"    # Drug databases are structured
      config:
        format: "json"
        schema:
          - "drug_name"
          - "generic_name"
          - "drug_class"
          - "indications"
          - "contraindications"
          - "interactions"
          - "dosing"
          - "warnings"
    
    extractors:
      # Drug interaction extraction
      - type: "DrugInteractionExtractor"
        config:
          interaction_types:
            - "drug-drug"
            - "drug-food"
            - "drug-disease"
            - "drug-lab"
          severity_levels:
            - "contraindicated"
            - "major"
            - "moderate" 
            - "minor"
          include_mechanism: true      # Interaction mechanism
      
      # Dosing information extraction
      - type: "DosingExtractor"
        config:
          populations:
            - "adult"
            - "pediatric"
            - "geriatric"
            - "renal_impairment"
            - "hepatic_impairment"
          routes:
            - "oral"
            - "iv"
            - "im"
            - "topical"
          extract_adjustments: true
      
      # Pharmacology extraction
      - type: "PharmacologyExtractor"
        config:
          properties:
            - "mechanism_of_action"
            - "pharmacokinetics"
            - "half_life"
            - "metabolism"
            - "excretion"
    
    embedder:
      type: "ChemBertEmbedder"         # Chemical structure aware
      config:
        model: "seyonec/ChemBERTa-zinc-base-v1"
        dimension: 768
        batch_size: 32
    
    vector_store:
      type: "ChromaStore"
      config:
        collection_name: "drug_information"
        persist_directory: "./vectordb/medical/drugs"
        metadata_config:
          indexed_fields: ["drug_class", "schedule", "formulary_status"]
    
    retrieval_strategy:
      type: "HybridUniversalStrategy"
      config:
        strategies:
          # Exact drug name matching
          - type: "ExactMatchStrategy"
            weight: 0.4
            config:
              fields: ["drug_name", "generic_name"]
          # Similarity for related drugs
          - type: "BasicSimilarityStrategy"
            weight: 0.6
            config:
              top_k: 10
        fusion_method: "weighted"
        final_k: 5

# ============================================================================
# PATIENT EDUCATION STRATEGY
# ============================================================================
patient_education_materials:
  description: "Patient-friendly educational content and discharge instructions"
  use_cases:
    - "Patient education"
    - "Discharge planning"
    - "Medication counseling"
    - "Lifestyle modification guidance"
  
  components:
    parser:
      type: "MarkdownParser"           # Many materials in markdown
      config:
        preserve_formatting: true
        extract_images: true          # Educational diagrams
        chunk_size: 512
        chunk_overlap: 50
    
    extractors:
      # Readability assessment
      - type: "ReadabilityExtractor"
        config:
          metrics:
            - "flesch_kincaid_grade"  # Grade level
            - "flesch_reading_ease"   # Ease score
            - "gunning_fog"           # Complexity
          target_grade_level: 8        # 8th grade reading level
          flag_complex: true           # Flag materials above target
      
      # Health literacy optimization
      - type: "HealthLiteracyExtractor"
        config:
          identify_jargon: true        # Medical terms to explain
          suggest_simplifications: true
          extract_key_points: true
          max_points: 5
      
      # Multilingual support
      - type: "LanguageExtractor"
        config:
          detect_language: true
          supported_languages:
            - "en"
            - "es"
            - "zh"
            - "vi"
            - "ar"
          extract_translations: true
    
    embedder:
      type: "MultilingualEmbedder"
      config:
        model: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
        dimension: 768
        batch_size: 32
    
    vector_store:
      type: "ChromaStore"
      config:
        collection_name: "patient_education"
        persist_directory: "./vectordb/medical/education"
        metadata_config:
          indexed_fields: ["condition", "language", "reading_level"]
    
    retrieval_strategy:
      type: "PersonalizedStrategy"    # Custom strategy for patient matching
      config:
        top_k: 5
        personalization_factors:
          language: 0.3               # Match patient's language
          reading_level: 0.2          # Match literacy level
          condition: 0.3              # Match medical condition
          age_appropriate: 0.2        # Age-appropriate content

# ============================================================================
# CLINICAL DECISION SUPPORT STRATEGY
# ============================================================================
clinical_decision_support:
  description: "Real-time clinical decision support combining all medical knowledge sources"
  use_cases:
    - "Differential diagnosis"
    - "Treatment recommendations"
    - "Risk assessment"
    - "Quality measure compliance"
  
  components:
    parser:
      type: "UniversalParser"
      config:
        auto_detect: true
        chunk_size: 768
        chunk_overlap: 150
    
    extractors:
      # Clinical criteria extraction
      - type: "ClinicalCriteriaExtractor"
        config:
          criteria_types:
            - "diagnostic"             # Diagnostic criteria
            - "screening"              # Screening guidelines
            - "treatment"              # Treatment algorithms
          extract_logic: true          # IF-THEN rules
          extract_thresholds: true     # Clinical thresholds
      
      # Risk score calculation
      - type: "RiskScoreExtractor"
        config:
          scores:
            - "CHADS2"                # Stroke risk
            - "ASCVD"                 # Cardiovascular risk
            - "MELD"                  # Liver disease
            - "GCS"                   # Glasgow Coma Scale
          extract_components: true
          calculate_if_possible: true
      
      # Quality measure extraction
      - type: "QualityMeasureExtractor"
        config:
          measure_sets:
            - "HEDIS"                 # Healthcare effectiveness
            - "CMS"                   # Medicare measures
            - "MIPS"                  # Merit-based incentive
          extract_numerator: true
          extract_denominator: true
          extract_exclusions: true
    
    embedder:
      type: "ClinicalBertEmbedder"
      config:
        model: "emilyalsentzer/Bio_ClinicalBERT"
        dimension: 768
        batch_size: 16
    
    vector_store:
      type: "ChromaStore"
      config:
        collection_name: "clinical_decision_support"
        persist_directory: "./vectordb/medical/cds"
    
    retrieval_strategy:
      type: "MultiQueryStrategy"
      config:
        num_queries: 4                # Multiple clinical perspectives
        query_variations:
          - "diagnosis"               # Diagnostic considerations
          - "treatment"               # Treatment options
          - "complications"           # Potential complications
          - "guidelines"              # Relevant guidelines
        aggregation: "rrf"
        top_k_per_query: 8
        final_k: 10