version: v1

prompts:
  - name: "customer_support"
    prompt: "You are a helpful customer support assistant. Answer questions politely and accurately."
    description: "Default customer support prompt"

rag:
  parser:
    type: CustomerSupportCSVParser
    config:
      content_fields: ["question", "answer"]
      metadata_fields: ["category", "timestamp"]

  embedder:
    type: OllamaEmbedder
    config:
      model: "mxbai-embed-large"
      batch_size: 32

  vector_store:
    type: ChromaStore
    config:
      collection_name: "customer_support"
      persist_directory: "./data/chroma"

models:
  - provider: "local"
    model: "llama3.1:8b"
  - provider: "openai"
    model: "gpt-4"
