name: chroma_store
type: store
class_name: ChromaStore
description: ChromaStore component
version: 1.0.0
dependencies:
  optional: []
  required: []
config_schema:
  type: object
  properties: {}
use_cases: []
