// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package config

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import "reflect"
import "regexp"
import "strings"

type LlamaFarmConfig struct {
	// List of dataset configurations
	Datasets []LlamaFarmConfigDatasetsElem `json:"datasets,omitempty" yaml:"datasets,omitempty" mapstructure:"datasets,omitempty"`

	// Model Context Protocol (MCP) client configuration
	Mcp *LlamaFarmConfigMcp `json:"mcp,omitempty" yaml:"mcp,omitempty" mapstructure:"mcp,omitempty"`

	// Project name
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Project namespace
	Namespace string `json:"namespace" yaml:"namespace" mapstructure:"namespace"`

	// List of named prompt sets
	Prompts []PromptSet `json:"prompts,omitempty" yaml:"prompts,omitempty" mapstructure:"prompts,omitempty"`

	// Schema for RAG system strategy configurations
	Rag *RAGStrategyConfigurationSchema `json:"rag,omitempty" yaml:"rag,omitempty" mapstructure:"rag,omitempty"`

	// Runtime corresponds to the JSON schema field "runtime".
	Runtime LlamaFarmConfigRuntime `json:"runtime" yaml:"runtime" mapstructure:"runtime"`

	// Config version, must be "v1"
	Version LlamaFarmConfigVersion `json:"version" yaml:"version" mapstructure:"version"`

	// Voice chat configuration for real-time speech interaction via WebSocket
	Voice *LlamaFarmConfigVoice `json:"voice,omitempty" yaml:"voice,omitempty" mapstructure:"voice,omitempty"`
}

type LlamaFarmConfigDatasetsElem struct {
	// Whether to automatically process uploads into the vector store
	AutoProcess bool `json:"auto_process,omitempty" yaml:"auto_process,omitempty" mapstructure:"auto_process,omitempty"`

	// RAG data processing strategy to use for the dataset. Defaults to universal_rag
	// if not specified.
	DataProcessingStrategy string `json:"data_processing_strategy,omitempty" yaml:"data_processing_strategy,omitempty" mapstructure:"data_processing_strategy,omitempty"`

	// RAG database to use for the dataset
	Database string `json:"database" yaml:"database" mapstructure:"database"`

	// Dataset name
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigDatasetsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["database"]; raw != nil && !ok {
		return fmt.Errorf("field database in LlamaFarmConfigDatasetsElem: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LlamaFarmConfigDatasetsElem: required")
	}
	type Plain LlamaFarmConfigDatasetsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["auto_process"]; !ok || v == nil {
		plain.AutoProcess = true
	}
	if v, ok := raw["data_processing_strategy"]; !ok || v == nil {
		plain.DataProcessingStrategy = "universal_rag"
	}
	*j = LlamaFarmConfigDatasetsElem(plain)
	return nil
}

// Model Context Protocol (MCP) client configuration
type LlamaFarmConfigMcp struct {
	// List of MCP Servers available to the project during inference
	Servers []LlamaFarmConfigMcpServersElem `json:"servers,omitempty" yaml:"servers,omitempty" mapstructure:"servers,omitempty"`
}

type LlamaFarmConfigMcpServersElem struct {
	// Optional args for the stdio command
	Args []string `json:"args,omitempty" yaml:"args,omitempty" mapstructure:"args,omitempty"`

	// Base URL of the MCP server (http)
	BaseUrl *string `json:"base_url,omitempty" yaml:"base_url,omitempty" mapstructure:"base_url,omitempty"`

	// Command/binary to launch the MCP server (stdio)
	Command *string `json:"command,omitempty" yaml:"command,omitempty" mapstructure:"command,omitempty"`

	// Environment variables for the stdio command
	Env LlamaFarmConfigMcpServersElemEnv `json:"env,omitempty" yaml:"env,omitempty" mapstructure:"env,omitempty"`

	// HTTP headers for the MCP server
	Headers LlamaFarmConfigMcpServersElemHeaders `json:"headers,omitempty" yaml:"headers,omitempty" mapstructure:"headers,omitempty"`

	// MCP server identifier
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Connection transport to the MCP server
	Transport LlamaFarmConfigMcpServersElemTransport `json:"transport" yaml:"transport" mapstructure:"transport"`
}

// Environment variables for the stdio command
type LlamaFarmConfigMcpServersElemEnv map[string]string

// HTTP headers for the MCP server
type LlamaFarmConfigMcpServersElemHeaders map[string]string

type LlamaFarmConfigMcpServersElemTransport string

const LlamaFarmConfigMcpServersElemTransportHttp LlamaFarmConfigMcpServersElemTransport = "http"
const LlamaFarmConfigMcpServersElemTransportSse LlamaFarmConfigMcpServersElemTransport = "sse"
const LlamaFarmConfigMcpServersElemTransportStdio LlamaFarmConfigMcpServersElemTransport = "stdio"

var enumValues_LlamaFarmConfigMcpServersElemTransport = []interface{}{
	"stdio",
	"http",
	"sse",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigMcpServersElemTransport) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LlamaFarmConfigMcpServersElemTransport {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LlamaFarmConfigMcpServersElemTransport, v)
	}
	*j = LlamaFarmConfigMcpServersElemTransport(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigMcpServersElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LlamaFarmConfigMcpServersElem: required")
	}
	if _, ok := raw["transport"]; raw != nil && !ok {
		return fmt.Errorf("field transport in LlamaFarmConfigMcpServersElem: required")
	}
	type Plain LlamaFarmConfigMcpServersElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = LlamaFarmConfigMcpServersElem(plain)
	return nil
}

// Processing pipeline configuration for parsers and extractors
type LlamaFarmConfigRagDataProcessingStrategiesElem struct {
	// Strategy description
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Metadata and feature extractors
	Extractors []LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElem `json:"extractors,omitempty" yaml:"extractors,omitempty" mapstructure:"extractors,omitempty"`

	// Unique strategy identifier
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Document parsers in processing order
	Parsers []LlamaFarmConfigRagDataProcessingStrategiesElemParsersElem `json:"parsers" yaml:"parsers" mapstructure:"parsers"`
}

type LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElem struct {
	// Optional condition for when to use this extractor
	Condition LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElemCondition `json:"condition,omitempty" yaml:"condition,omitempty" mapstructure:"condition,omitempty"`

	// Extractor configuration
	Config LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElemConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Glob patterns for files to apply this extractor to
	FileIncludePatterns []string `json:"file_include_patterns,omitempty" yaml:"file_include_patterns,omitempty" mapstructure:"file_include_patterns,omitempty"`

	// Extractor priority (lower = apply first)
	Priority int `json:"priority,omitempty" yaml:"priority,omitempty" mapstructure:"priority,omitempty"`

	// Database names that require this extractor
	RequiredFor *LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElemRequiredFor `json:"required_for,omitempty" yaml:"required_for,omitempty" mapstructure:"required_for,omitempty"`

	// Extractor type
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// Optional condition for when to use this extractor
type LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElemCondition *string

// Extractor configuration
type LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElemConfig map[string]interface{}

// Database names that require this extractor
type LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElemRequiredFor []string

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElem: required")
	}
	type Plain LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["priority"]; !ok || v == nil {
		plain.Priority = 50.0
	}
	if 1000 < plain.Priority {
		return fmt.Errorf("field %s: must be <= %v", "priority", 1000)
	}
	if 0 > plain.Priority {
		return fmt.Errorf("field %s: must be >= %v", "priority", 0)
	}
	*j = LlamaFarmConfigRagDataProcessingStrategiesElemExtractorsElem(plain)
	return nil
}

type LlamaFarmConfigRagDataProcessingStrategiesElemParsersElem struct {
	// Parser configuration
	Config LlamaFarmConfigRagDataProcessingStrategiesElemParsersElemConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Parser to use if this one fails
	FallbackParser LlamaFarmConfigRagDataProcessingStrategiesElemParsersElemFallbackParser `json:"fallback_parser,omitempty" yaml:"fallback_parser,omitempty" mapstructure:"fallback_parser,omitempty"`

	// File extensions this parser handles (e.g., [".pdf", ".PDF"])
	FileExtensions *LlamaFarmConfigRagDataProcessingStrategiesElemParsersElemFileExtensions `json:"file_extensions,omitempty" yaml:"file_extensions,omitempty" mapstructure:"file_extensions,omitempty"`

	// Glob patterns for files to include (e.g., ["*.pdf", "report_*.pdf"])
	FileIncludePatterns []string `json:"file_include_patterns,omitempty" yaml:"file_include_patterns,omitempty" mapstructure:"file_include_patterns,omitempty"`

	// MIME types this parser handles (e.g., ["application/pdf"])
	MimeTypes *LlamaFarmConfigRagDataProcessingStrategiesElemParsersElemMimeTypes `json:"mime_types,omitempty" yaml:"mime_types,omitempty" mapstructure:"mime_types,omitempty"`

	// Parser priority (lower = try first)
	Priority int `json:"priority,omitempty" yaml:"priority,omitempty" mapstructure:"priority,omitempty"`

	// Parser type identifier (e.g., PDFParser_PyPDF2, TextParser_LlamaIndex)
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

// Parser configuration
type LlamaFarmConfigRagDataProcessingStrategiesElemParsersElemConfig map[string]interface{}

// Parser to use if this one fails
type LlamaFarmConfigRagDataProcessingStrategiesElemParsersElemFallbackParser *string

// File extensions this parser handles (e.g., [".pdf", ".PDF"])
type LlamaFarmConfigRagDataProcessingStrategiesElemParsersElemFileExtensions []string

// MIME types this parser handles (e.g., ["application/pdf"])
type LlamaFarmConfigRagDataProcessingStrategiesElemParsersElemMimeTypes []string

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRagDataProcessingStrategiesElemParsersElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain LlamaFarmConfigRagDataProcessingStrategiesElemParsersElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["priority"]; !ok || v == nil {
		plain.Priority = 50.0
	}
	if 1000 < plain.Priority {
		return fmt.Errorf("field %s: must be <= %v", "priority", 1000)
	}
	if 0 > plain.Priority {
		return fmt.Errorf("field %s: must be >= %v", "priority", 0)
	}
	if plain.Type != nil {
		if matched, _ := regexp.MatchString(`^[A-Za-z][A-Za-z0-9_]*Parser[A-Za-z0-9_]*$|^DirectoryParser$`, string(*plain.Type)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "Type", `^[A-Za-z][A-Za-z0-9_]*Parser[A-Za-z0-9_]*$|^DirectoryParser$`)
		}
	}
	*j = LlamaFarmConfigRagDataProcessingStrategiesElemParsersElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRagDataProcessingStrategiesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LlamaFarmConfigRagDataProcessingStrategiesElem: required")
	}
	if _, ok := raw["parsers"]; raw != nil && !ok {
		return fmt.Errorf("field parsers in LlamaFarmConfigRagDataProcessingStrategiesElem: required")
	}
	type Plain LlamaFarmConfigRagDataProcessingStrategiesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Description != nil && len(*plain.Description) < 10 {
		return fmt.Errorf("field %s length: must be >= %d", "description", 10)
	}
	if plain.Description != nil && len(*plain.Description) > 500 {
		return fmt.Errorf("field %s length: must be <= %d", "description", 500)
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9_]*$`, string(plain.Name)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Name", `^[a-z][a-z0-9_]*$`)
	}
	if len(plain.Name) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if len(plain.Name) > 50 {
		return fmt.Errorf("field %s length: must be <= %d", "name", 50)
	}
	if plain.Parsers != nil && len(plain.Parsers) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "parsers", 1)
	}
	*j = LlamaFarmConfigRagDataProcessingStrategiesElem(plain)
	return nil
}

// Database configuration with embedded embedding/retrieval strategies
type LlamaFarmConfigRagDatabasesElem struct {
	// Database-specific configuration
	Config LlamaFarmConfigRagDatabasesElemConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Name of the default embedding strategy to use
	DefaultEmbeddingStrategy *string `json:"default_embedding_strategy,omitempty" yaml:"default_embedding_strategy,omitempty" mapstructure:"default_embedding_strategy,omitempty"`

	// Name of the default retrieval strategy to use
	DefaultRetrievalStrategy *string `json:"default_retrieval_strategy,omitempty" yaml:"default_retrieval_strategy,omitempty" mapstructure:"default_retrieval_strategy,omitempty"`

	// Multiple embedding strategies for hybrid search
	EmbeddingStrategies []LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElem `json:"embedding_strategies,omitempty" yaml:"embedding_strategies,omitempty" mapstructure:"embedding_strategies,omitempty"`

	// Unique database identifier
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Multiple retrieval strategies for different query patterns
	RetrievalStrategies []LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElem `json:"retrieval_strategies,omitempty" yaml:"retrieval_strategies,omitempty" mapstructure:"retrieval_strategies,omitempty"`

	// Database type (accepts both short names and Store class names)
	Type LlamaFarmConfigRagDatabasesElemType `json:"type" yaml:"type" mapstructure:"type"`
}

// Database-specific configuration
type LlamaFarmConfigRagDatabasesElemConfig map[string]interface{}

type LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElem struct {
	// Optional condition for when to use this embedding (e.g., doc.type == 'code')
	Condition LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemCondition `json:"condition,omitempty" yaml:"condition,omitempty" mapstructure:"condition,omitempty"`

	// Embedder configuration
	Config LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Strategy identifier
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Priority for automatic selection
	Priority int `json:"priority,omitempty" yaml:"priority,omitempty" mapstructure:"priority,omitempty"`

	// Embedding type
	Type LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType `json:"type" yaml:"type" mapstructure:"type"`
}

// Optional condition for when to use this embedding (e.g., doc.type == 'code')
type LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemCondition *string

// Embedder configuration
type LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemConfig map[string]interface{}

type LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType string

const LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemTypeHuggingFaceEmbedder LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType = "HuggingFaceEmbedder"
const LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemTypeOllamaEmbedder LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType = "OllamaEmbedder"
const LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemTypeOpenAIEmbedder LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType = "OpenAIEmbedder"
const LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemTypeSentenceTransformerEmbedder LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType = "SentenceTransformerEmbedder"
const LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemTypeUniversalEmbedder LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType = "UniversalEmbedder"

var enumValues_LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType = []interface{}{
	"HuggingFaceEmbedder",
	"OllamaEmbedder",
	"OpenAIEmbedder",
	"SentenceTransformerEmbedder",
	"UniversalEmbedder",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType, v)
	}
	*j = LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElem: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElem: required")
	}
	type Plain LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["priority"]; !ok || v == nil {
		plain.Priority = 0.0
	}
	*j = LlamaFarmConfigRagDatabasesElemEmbeddingStrategiesElem(plain)
	return nil
}

type LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElem struct {
	// Retrieval configuration
	Config LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Whether this is the default strategy
	Default bool `json:"default,omitempty" yaml:"default,omitempty" mapstructure:"default,omitempty"`

	// Strategy identifier
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Retrieval type
	Type LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType `json:"type" yaml:"type" mapstructure:"type"`
}

// Retrieval configuration
type LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemConfig map[string]interface{}

type LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType string

const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeBM25Retriever LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "BM25Retriever"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeBasicSimilarityStrategy LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "BasicSimilarityStrategy"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeCrossEncoderRerankedStrategy LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "CrossEncoderRerankedStrategy"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeElasticRetriever LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "ElasticRetriever"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeGraphRetriever LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "GraphRetriever"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeHybridRetriever LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "HybridRetriever"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeHybridUniversalStrategy LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "HybridUniversalStrategy"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeMetadataFilteredStrategy LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "MetadataFilteredStrategy"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeMultiQueryStrategy LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "MultiQueryStrategy"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeMultiTurnRAGStrategy LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "MultiTurnRAGStrategy"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeRerankedRetriever LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "RerankedRetriever"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeRerankedStrategy LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "RerankedStrategy"
const LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemTypeVectorRetriever LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = "VectorRetriever"

var enumValues_LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType = []interface{}{
	"VectorRetriever",
	"HybridRetriever",
	"BM25Retriever",
	"RerankedRetriever",
	"GraphRetriever",
	"ElasticRetriever",
	"BasicSimilarityStrategy",
	"MetadataFilteredStrategy",
	"MultiQueryStrategy",
	"RerankedStrategy",
	"HybridUniversalStrategy",
	"CrossEncoderRerankedStrategy",
	"MultiTurnRAGStrategy",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType, v)
	}
	*j = LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElem: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElem: required")
	}
	type Plain LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["default"]; !ok || v == nil {
		plain.Default = false
	}
	*j = LlamaFarmConfigRagDatabasesElemRetrievalStrategiesElem(plain)
	return nil
}

type LlamaFarmConfigRagDatabasesElemType string

const LlamaFarmConfigRagDatabasesElemTypeChromaStore LlamaFarmConfigRagDatabasesElemType = "ChromaStore"
const LlamaFarmConfigRagDatabasesElemTypeQdrantStore LlamaFarmConfigRagDatabasesElemType = "QdrantStore"

var enumValues_LlamaFarmConfigRagDatabasesElemType = []interface{}{
	"ChromaStore",
	"QdrantStore",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRagDatabasesElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LlamaFarmConfigRagDatabasesElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LlamaFarmConfigRagDatabasesElemType, v)
	}
	*j = LlamaFarmConfigRagDatabasesElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRagDatabasesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LlamaFarmConfigRagDatabasesElem: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in LlamaFarmConfigRagDatabasesElem: required")
	}
	type Plain LlamaFarmConfigRagDatabasesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9_]*$`, string(plain.Name)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Name", `^[a-z][a-z0-9_]*$`)
	}
	if len(plain.Name) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if len(plain.Name) > 50 {
		return fmt.Errorf("field %s length: must be <= %d", "name", 50)
	}
	*j = LlamaFarmConfigRagDatabasesElem(plain)
	return nil
}

type LlamaFarmConfigRuntime struct {
	// Name of the default model to use (references a model name in the models list).
	// If not specified, uses first model.
	DefaultModel *string `json:"default_model,omitempty" yaml:"default_model,omitempty" mapstructure:"default_model,omitempty"`

	// List of model configurations for multi-model support
	Models []LlamaFarmConfigRuntimeModelsElem `json:"models,omitempty" yaml:"models,omitempty" mapstructure:"models,omitempty"`
}

type LlamaFarmConfigRuntimeModelsElem struct {
	// API key for the provider
	ApiKey *string `json:"api_key,omitempty" yaml:"api_key,omitempty" mapstructure:"api_key,omitempty"`

	// Base URL for the provider
	BaseUrl *string `json:"base_url,omitempty" yaml:"base_url,omitempty" mapstructure:"base_url,omitempty"`

	// Human-readable description of this model configuration
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Configuration for BERT-style encoder models (Universal runtime only).
	// Used for embeddings, classification, reranking, and NER endpoints.
	//
	EncoderConfig *LlamaFarmConfigRuntimeModelsElemEncoderConfig `json:"encoder_config,omitempty" yaml:"encoder_config,omitempty" mapstructure:"encoder_config,omitempty"`

	// Provider-specific parameters passed in the request body's extra_body field.
	// These parameters are sent directly to the underlying provider API.
	//
	// Note: For GGUF quantization, specify it in the model name using the format
	// "model_id:quantization" (e.g., "unsloth/Qwen3-4B-GGUF:Q4_K_M").
	//
	// The properties below document common GGUF/llama.cpp parameters, but any
	// additional parameters will be passed through to the provider.
	//
	ExtraBody *LlamaFarmConfigRuntimeModelsElemExtraBody `json:"extra_body,omitempty" yaml:"extra_body,omitempty" mapstructure:"extra_body,omitempty"`

	// Instructor mode to use for structured output (e.g., tools, json, md_json)
	InstructorMode *string `json:"instructor_mode,omitempty" yaml:"instructor_mode,omitempty" mapstructure:"instructor_mode,omitempty"`

	// Keep this model loaded in memory to prevent cache eviction.
	// When true, the runtime will not purge this model from cache
	// even under memory pressure. Useful for models that need fast
	// response times (e.g., voice chat LLMs).
	//
	KeepLoaded bool `json:"keep_loaded,omitempty" yaml:"keep_loaded,omitempty" mapstructure:"keep_loaded,omitempty"`

	// List of MCP server names to use for this model (omit to use all servers, empty
	// list for none)
	McpServers []string `json:"mcp_servers,omitempty" yaml:"mcp_servers,omitempty" mapstructure:"mcp_servers,omitempty"`

	// Model name or ID
	Model string `json:"model" yaml:"model" mapstructure:"model"`

	// Additional parameters passed directly to the API provider as request
	// parameters.
	// Common examples: temperature, top_p, max_tokens, frequency_penalty, etc.
	//
	ModelApiParameters LlamaFarmConfigRuntimeModelsElemModelApiParameters `json:"model_api_parameters,omitempty" yaml:"model_api_parameters,omitempty" mapstructure:"model_api_parameters,omitempty"`

	// Model identifier (unique name)
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// List of prompt set names to use for this model (merged in order)
	Prompts []string `json:"prompts,omitempty" yaml:"prompts,omitempty" mapstructure:"prompts,omitempty"`

	// Runtime provider for this model
	Provider LlamaFarmConfigRuntimeModelsElemProvider `json:"provider" yaml:"provider" mapstructure:"provider"`

	// Strategy to use for tool calls. `native_api` uses native tool calling through
	// the client
	// library (e.g. setting the `tools` parameter on the chat completions OpenAI
	// request);
	// `prompt_based` uses system prompting to inject tool definitions and
	// instructions to guide
	// any model to use tools. This is universal, but may not be as effective as
	// native tool calling.
	// Use `prompt_based` for models that do not support native tool calling.
	//
	ToolCallStrategy LlamaFarmConfigRuntimeModelsElemToolCallStrategy `json:"tool_call_strategy,omitempty" yaml:"tool_call_strategy,omitempty" mapstructure:"tool_call_strategy,omitempty"`

	// List of tools to use for this model
	Tools []LlamaFarmConfigRuntimeModelsElemToolsElem `json:"tools,omitempty" yaml:"tools,omitempty" mapstructure:"tools,omitempty"`
}

// Configuration for BERT-style encoder models (Universal runtime only).
// Used for embeddings, classification, reranking, and NER endpoints.
type LlamaFarmConfigRuntimeModelsElemEncoderConfig struct {
	// Maximum sequence length for tokenization. Auto-detected if not specified.
	// ModernBERT supports up to 8,192 tokens, classic BERT supports 512.
	// Must be a positive integer if specified.
	//
	MaxLength *int `json:"max_length,omitempty" yaml:"max_length,omitempty" mapstructure:"max_length,omitempty"`

	// Task type for the encoder model:
	// - embedding: Generate dense vector representations
	// - classification: Sentiment, spam detection, intent routing
	// - reranking: Cross-encoder document reranking
	// - ner: Named entity recognition
	//
	Task LlamaFarmConfigRuntimeModelsElemEncoderConfigTask `json:"task,omitempty" yaml:"task,omitempty" mapstructure:"task,omitempty"`

	// Enable Flash Attention 2 for faster inference on CUDA devices.
	// Requires flash_attn package and compatible GPU.
	//
	UseFlashAttention bool `json:"use_flash_attention,omitempty" yaml:"use_flash_attention,omitempty" mapstructure:"use_flash_attention,omitempty"`
}

type LlamaFarmConfigRuntimeModelsElemEncoderConfigTask string

const LlamaFarmConfigRuntimeModelsElemEncoderConfigTaskClassification LlamaFarmConfigRuntimeModelsElemEncoderConfigTask = "classification"
const LlamaFarmConfigRuntimeModelsElemEncoderConfigTaskEmbedding LlamaFarmConfigRuntimeModelsElemEncoderConfigTask = "embedding"
const LlamaFarmConfigRuntimeModelsElemEncoderConfigTaskNer LlamaFarmConfigRuntimeModelsElemEncoderConfigTask = "ner"
const LlamaFarmConfigRuntimeModelsElemEncoderConfigTaskReranking LlamaFarmConfigRuntimeModelsElemEncoderConfigTask = "reranking"

var enumValues_LlamaFarmConfigRuntimeModelsElemEncoderConfigTask = []interface{}{
	"embedding",
	"classification",
	"reranking",
	"ner",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRuntimeModelsElemEncoderConfigTask) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LlamaFarmConfigRuntimeModelsElemEncoderConfigTask {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LlamaFarmConfigRuntimeModelsElemEncoderConfigTask, v)
	}
	*j = LlamaFarmConfigRuntimeModelsElemEncoderConfigTask(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRuntimeModelsElemEncoderConfig) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain LlamaFarmConfigRuntimeModelsElemEncoderConfig
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.MaxLength != nil && 1 > *plain.MaxLength {
		return fmt.Errorf("field %s: must be >= %v", "max_length", 1)
	}
	if v, ok := raw["task"]; !ok || v == nil {
		plain.Task = "embedding"
	}
	if v, ok := raw["use_flash_attention"]; !ok || v == nil {
		plain.UseFlashAttention = true
	}
	*j = LlamaFarmConfigRuntimeModelsElemEncoderConfig(plain)
	return nil
}

// Provider-specific parameters passed in the request body's extra_body field.
// These parameters are sent directly to the underlying provider API.
//
// Note: For GGUF quantization, specify it in the model name using the format
// "model_id:quantization" (e.g., "unsloth/Qwen3-4B-GGUF:Q4_K_M").
//
// The properties below document common GGUF/llama.cpp parameters, but any
// additional parameters will be passed through to the provider.
type LlamaFarmConfigRuntimeModelsElemExtraBody struct {
	// KV cache key quantization type. Lower precision reduces memory usage.
	// Common values: f32 (full), f16 (half), q8_0, q5_1, q5_0, q4_1, q4_0.
	// Using q4_0 can reduce KV cache memory by ~4x vs f16.
	//
	CacheTypeK *string `json:"cache_type_k,omitempty" yaml:"cache_type_k,omitempty" mapstructure:"cache_type_k,omitempty"`

	// KV cache value quantization type. Lower precision reduces memory usage.
	// Common values: f32 (full), f16 (half), q8_0, q5_1, q5_0, q4_1, q4_0.
	// Using q4_0 can reduce KV cache memory by ~4x vs f16.
	//
	CacheTypeV *string `json:"cache_type_v,omitempty" yaml:"cache_type_v,omitempty" mapstructure:"cache_type_v,omitempty"`

	// Enable flash attention for faster inference. Requires GPU support.
	// Recommended for Ampere+ GPUs (RTX 30xx, A100, Jetson Orin).
	//
	FlashAttn *bool `json:"flash_attn,omitempty" yaml:"flash_attn,omitempty" mapstructure:"flash_attn,omitempty"`

	// Batch size for prompt processing. Controls compute buffer memory usage.
	// Lower values (e.g., 512) reduce memory significantly at slight speed cost.
	// Critical for memory-constrained devices like Jetson (8GB shared memory).
	//
	NBatch *int `json:"n_batch,omitempty" yaml:"n_batch,omitempty" mapstructure:"n_batch,omitempty"`

	// Context window size for GGUF models (Universal runtime only).
	// If not specified, automatically computed based on available memory,
	// model training context, and pattern-based defaults.
	// See Universal runtime documentation for auto-detection behavior.
	//
	NCtx *int `json:"n_ctx,omitempty" yaml:"n_ctx,omitempty" mapstructure:"n_ctx,omitempty"`

	// Number of layers to offload to GPU. Use -1 to offload all layers.
	// For models like Qwen3-1.7B with 29 layers, use 29 for full GPU offload.
	//
	NGpuLayers *int `json:"n_gpu_layers,omitempty" yaml:"n_gpu_layers,omitempty" mapstructure:"n_gpu_layers,omitempty"`

	// Number of CPU threads to use. If not specified, auto-detected.
	// For Jetson Orin Nano, use 6 (number of CPU cores).
	//
	NThreads *int `json:"n_threads,omitempty" yaml:"n_threads,omitempty" mapstructure:"n_threads,omitempty"`

	// Lock model in RAM to prevent swapping. Default: false.
	// Set to false on memory-constrained devices (e.g., 8GB Jetson) to allow
	// OS memory management.
	//
	UseMlock *bool `json:"use_mlock,omitempty" yaml:"use_mlock,omitempty" mapstructure:"use_mlock,omitempty"`

	// Memory-map model file for efficient memory usage. Default: true.
	// Enables OS to swap model pages efficiently on memory-constrained devices.
	//
	UseMmap *bool `json:"use_mmap,omitempty" yaml:"use_mmap,omitempty" mapstructure:"use_mmap,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRuntimeModelsElemExtraBody) UnmarshalJSON(value []byte) error {
	type Plain LlamaFarmConfigRuntimeModelsElemExtraBody
	var plain Plain
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.NBatch != nil && 1 > *plain.NBatch {
		return fmt.Errorf("field %s: must be >= %v", "n_batch", 1)
	}
	if plain.NGpuLayers != nil && -1 > *plain.NGpuLayers {
		return fmt.Errorf("field %s: must be >= %v", "n_gpu_layers", -1)
	}
	if plain.NThreads != nil && 1 > *plain.NThreads {
		return fmt.Errorf("field %s: must be >= %v", "n_threads", 1)
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = LlamaFarmConfigRuntimeModelsElemExtraBody(plain)
	return nil
}

// Additional parameters passed directly to the API provider as request parameters.
// Common examples: temperature, top_p, max_tokens, frequency_penalty, etc.
type LlamaFarmConfigRuntimeModelsElemModelApiParameters map[string]interface{}

type LlamaFarmConfigRuntimeModelsElemProvider string

const LlamaFarmConfigRuntimeModelsElemProviderLemonade LlamaFarmConfigRuntimeModelsElemProvider = "lemonade"
const LlamaFarmConfigRuntimeModelsElemProviderOllama LlamaFarmConfigRuntimeModelsElemProvider = "ollama"
const LlamaFarmConfigRuntimeModelsElemProviderOpenai LlamaFarmConfigRuntimeModelsElemProvider = "openai"
const LlamaFarmConfigRuntimeModelsElemProviderUniversal LlamaFarmConfigRuntimeModelsElemProvider = "universal"

var enumValues_LlamaFarmConfigRuntimeModelsElemProvider = []interface{}{
	"openai",
	"ollama",
	"lemonade",
	"universal",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRuntimeModelsElemProvider) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LlamaFarmConfigRuntimeModelsElemProvider {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LlamaFarmConfigRuntimeModelsElemProvider, v)
	}
	*j = LlamaFarmConfigRuntimeModelsElemProvider(v)
	return nil
}

type LlamaFarmConfigRuntimeModelsElemToolCallStrategy string

const LlamaFarmConfigRuntimeModelsElemToolCallStrategyNativeApi LlamaFarmConfigRuntimeModelsElemToolCallStrategy = "native_api"
const LlamaFarmConfigRuntimeModelsElemToolCallStrategyPromptBased LlamaFarmConfigRuntimeModelsElemToolCallStrategy = "prompt_based"

var enumValues_LlamaFarmConfigRuntimeModelsElemToolCallStrategy = []interface{}{
	"native_api",
	"prompt_based",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRuntimeModelsElemToolCallStrategy) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LlamaFarmConfigRuntimeModelsElemToolCallStrategy {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LlamaFarmConfigRuntimeModelsElemToolCallStrategy, v)
	}
	*j = LlamaFarmConfigRuntimeModelsElemToolCallStrategy(v)
	return nil
}

type LlamaFarmConfigRuntimeModelsElemToolsElem struct {
	// Description of the tool
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Name of the tool
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Parameters of the tool
	Parameters LlamaFarmConfigRuntimeModelsElemToolsElemParameters `json:"parameters" yaml:"parameters" mapstructure:"parameters"`

	// Type of tool
	Type LlamaFarmConfigRuntimeModelsElemToolsElemType `json:"type" yaml:"type" mapstructure:"type"`
}

// Parameters of the tool
type LlamaFarmConfigRuntimeModelsElemToolsElemParameters map[string]interface{}

type LlamaFarmConfigRuntimeModelsElemToolsElemType string

const LlamaFarmConfigRuntimeModelsElemToolsElemTypeFunction LlamaFarmConfigRuntimeModelsElemToolsElemType = "function"

var enumValues_LlamaFarmConfigRuntimeModelsElemToolsElemType = []interface{}{
	"function",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRuntimeModelsElemToolsElemType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LlamaFarmConfigRuntimeModelsElemToolsElemType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LlamaFarmConfigRuntimeModelsElemToolsElemType, v)
	}
	*j = LlamaFarmConfigRuntimeModelsElemToolsElemType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRuntimeModelsElemToolsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in LlamaFarmConfigRuntimeModelsElemToolsElem: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LlamaFarmConfigRuntimeModelsElemToolsElem: required")
	}
	if _, ok := raw["parameters"]; raw != nil && !ok {
		return fmt.Errorf("field parameters in LlamaFarmConfigRuntimeModelsElemToolsElem: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in LlamaFarmConfigRuntimeModelsElemToolsElem: required")
	}
	type Plain LlamaFarmConfigRuntimeModelsElemToolsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = LlamaFarmConfigRuntimeModelsElemToolsElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigRuntimeModelsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["model"]; raw != nil && !ok {
		return fmt.Errorf("field model in LlamaFarmConfigRuntimeModelsElem: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LlamaFarmConfigRuntimeModelsElem: required")
	}
	if _, ok := raw["provider"]; raw != nil && !ok {
		return fmt.Errorf("field provider in LlamaFarmConfigRuntimeModelsElem: required")
	}
	type Plain LlamaFarmConfigRuntimeModelsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["keep_loaded"]; !ok || v == nil {
		plain.KeepLoaded = false
	}
	if v, ok := raw["prompts"]; !ok || v == nil {
		plain.Prompts = []string{}
	}
	if v, ok := raw["tool_call_strategy"]; !ok || v == nil {
		plain.ToolCallStrategy = "native_api"
	}
	if v, ok := raw["tools"]; !ok || v == nil {
		plain.Tools = []LlamaFarmConfigRuntimeModelsElemToolsElem{}
	}
	*j = LlamaFarmConfigRuntimeModelsElem(plain)
	return nil
}

type LlamaFarmConfigVersion string

const LlamaFarmConfigVersionV1 LlamaFarmConfigVersion = "v1"

var enumValues_LlamaFarmConfigVersion = []interface{}{
	"v1",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigVersion) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LlamaFarmConfigVersion {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LlamaFarmConfigVersion, v)
	}
	*j = LlamaFarmConfigVersion(v)
	return nil
}

// Voice chat configuration for real-time speech interaction via WebSocket
type LlamaFarmConfigVoice struct {
	// Speech emotion recognition configuration. Analyzes user audio to detect
	// emotional tone (angry, happy, sad, etc.) and provides context to the LLM.
	//
	Emotion *LlamaFarmConfigVoiceEmotion `json:"emotion,omitempty" yaml:"emotion,omitempty" mapstructure:"emotion,omitempty"`

	// Enable thinking/reasoning mode for the LLM. When false (default),
	// the LLM is instructed to skip chain-of-thought reasoning and respond
	// directly. This is recommended for voice chat since thinking output
	// would be spoken aloud by TTS.
	//
	EnableThinking bool `json:"enable_thinking,omitempty" yaml:"enable_thinking,omitempty" mapstructure:"enable_thinking,omitempty"`

	// Enable or disable the voice chat endpoint
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Reference to a model name in runtime.models[] to use for voice chat.
	// The model's prompts array will be applied to voice conversations.
	//
	LlmModel *string `json:"llm_model,omitempty" yaml:"llm_model,omitempty" mapstructure:"llm_model,omitempty"`

	// Speech-to-text configuration
	Stt *LlamaFarmConfigVoiceStt `json:"stt,omitempty" yaml:"stt,omitempty" mapstructure:"stt,omitempty"`

	// Text-to-speech configuration
	Tts *LlamaFarmConfigVoiceTts `json:"tts,omitempty" yaml:"tts,omitempty" mapstructure:"tts,omitempty"`

	// End-of-turn detection configuration. Controls how the system detects
	// when a user has finished speaking vs when they're just pausing to think.
	// This prevents the LLM from responding prematurely during thinking pauses.
	//
	TurnDetection *LlamaFarmConfigVoiceTurnDetection `json:"turn_detection,omitempty" yaml:"turn_detection,omitempty" mapstructure:"turn_detection,omitempty"`
}

// Speech emotion recognition configuration. Analyzes user audio to detect
// emotional tone (angry, happy, sad, etc.) and provides context to the LLM.
type LlamaFarmConfigVoiceEmotion struct {
	// Minimum confidence threshold for emotion detection.
	// Predictions below this threshold are reported as 'neutral'.
	// Lower values increase sensitivity but may produce false positives.
	//
	ConfidenceThreshold float64 `json:"confidence_threshold,omitempty" yaml:"confidence_threshold,omitempty" mapstructure:"confidence_threshold,omitempty"`

	// Enable speech emotion recognition. When enabled, analyzes audio to
	// detect user emotional tone and includes it in the LLM context. This
	// allows the model to respond appropriately to user mood.
	//
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Emotion recognition model ID:
	// - wav2vec2-lg-xlsr-en: English emotion recognition (default, recommended)
	// - wav2vec2-base-superb: Alternative model from SUPERB benchmark
	// Custom HuggingFace model IDs are also supported.
	//
	Model string `json:"model,omitempty" yaml:"model,omitempty" mapstructure:"model,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigVoiceEmotion) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain LlamaFarmConfigVoiceEmotion
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["confidence_threshold"]; !ok || v == nil {
		plain.ConfidenceThreshold = 0.4
	}
	if 1 < plain.ConfidenceThreshold {
		return fmt.Errorf("field %s: must be <= %v", "confidence_threshold", 1)
	}
	if 0 > plain.ConfidenceThreshold {
		return fmt.Errorf("field %s: must be >= %v", "confidence_threshold", 0)
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = true
	}
	if v, ok := raw["model"]; !ok || v == nil {
		plain.Model = "wav2vec2-lg-xlsr-en"
	}
	*j = LlamaFarmConfigVoiceEmotion(plain)
	return nil
}

// Speech-to-text configuration
type LlamaFarmConfigVoiceStt struct {
	// Keep STT model loaded in memory to prevent cache eviction.
	// When true, the runtime will not purge this model from cache
	// even under memory pressure. Reduces latency for voice transcription.
	//
	KeepLoaded bool `json:"keep_loaded,omitempty" yaml:"keep_loaded,omitempty" mapstructure:"keep_loaded,omitempty"`

	// Language code for transcription (e.g., "en", "es", "fr")
	Language string `json:"language,omitempty" yaml:"language,omitempty" mapstructure:"language,omitempty"`

	// Whisper model size for transcription:
	// - tiny (39M, fastest, lower accuracy)
	// - base (74M, fast, good accuracy, default)
	// - small (244M, medium speed, better accuracy)
	// - medium (769M, slower, high accuracy)
	// - large-v3 (1.5B, slowest, highest accuracy)
	//
	Model LlamaFarmConfigVoiceSttModel `json:"model,omitempty" yaml:"model,omitempty" mapstructure:"model,omitempty"`
}

type LlamaFarmConfigVoiceSttModel string

const LlamaFarmConfigVoiceSttModelBase LlamaFarmConfigVoiceSttModel = "base"
const LlamaFarmConfigVoiceSttModelLargeV3 LlamaFarmConfigVoiceSttModel = "large-v3"
const LlamaFarmConfigVoiceSttModelMedium LlamaFarmConfigVoiceSttModel = "medium"
const LlamaFarmConfigVoiceSttModelSmall LlamaFarmConfigVoiceSttModel = "small"
const LlamaFarmConfigVoiceSttModelTiny LlamaFarmConfigVoiceSttModel = "tiny"

var enumValues_LlamaFarmConfigVoiceSttModel = []interface{}{
	"tiny",
	"base",
	"small",
	"medium",
	"large-v3",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigVoiceSttModel) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_LlamaFarmConfigVoiceSttModel {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_LlamaFarmConfigVoiceSttModel, v)
	}
	*j = LlamaFarmConfigVoiceSttModel(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigVoiceStt) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain LlamaFarmConfigVoiceStt
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["keep_loaded"]; !ok || v == nil {
		plain.KeepLoaded = false
	}
	if v, ok := raw["language"]; !ok || v == nil {
		plain.Language = "en"
	}
	if v, ok := raw["model"]; !ok || v == nil {
		plain.Model = "base"
	}
	*j = LlamaFarmConfigVoiceStt(plain)
	return nil
}

// Text-to-speech configuration
type LlamaFarmConfigVoiceTts struct {
	// Keep TTS model loaded in memory to prevent cache eviction.
	// When true, the runtime will not purge this model from cache
	// even under memory pressure. Reduces latency for voice responses.
	//
	KeepLoaded bool `json:"keep_loaded,omitempty" yaml:"keep_loaded,omitempty" mapstructure:"keep_loaded,omitempty"`

	// TTS model/backend ID:
	// - kokoro: High-quality neural TTS with built-in voices (default)
	// - chatterbox-turbo: Fast voice cloning TTS (350M params, sub-200ms)
	//   Requires voice_profiles configuration for voice cloning.
	// - pocket-tts: Lightweight CPU TTS from Kyutai (100M params, ~6x realtime)
	//   Fast and efficient, no GPU required.
	//
	Model string `json:"model,omitempty" yaml:"model,omitempty" mapstructure:"model,omitempty"`

	// Chatterbox Turbo repetition penalty (ignored for Kokoro).
	// Penalty applied to repeating tokens. Higher = less repetition.
	//
	RepetitionPenalty float64 `json:"repetition_penalty,omitempty" yaml:"repetition_penalty,omitempty" mapstructure:"repetition_penalty,omitempty"`

	// Speech speed multiplier (0.5-2.0). For more natural-sounding
	// speech, try 0.9-0.95 (slightly slower than default).
	// - 0.8-0.9: Slower, deliberate (good for complex topics)
	// - 0.9-0.95: Natural conversational pace (recommended)
	// - 1.0: Default speed
	// - 1.1-1.2: Faster, energetic
	//
	Speed float64 `json:"speed,omitempty" yaml:"speed,omitempty" mapstructure:"speed,omitempty"`

	// Chatterbox Turbo temperature (ignored for Kokoro).
	// Controls randomness in generation. Higher = more varied output.
	// - 0.5: More deterministic
	// - 0.8: Balanced (default)
	// - 1.2: More creative/varied
	//
	Temperature float64 `json:"temperature,omitempty" yaml:"temperature,omitempty" mapstructure:"temperature,omitempty"`

	// Chatterbox Turbo top-k sampling (ignored for Kokoro).
	// Number of highest probability tokens to consider.
	//
	TopK int `json:"top_k,omitempty" yaml:"top_k,omitempty" mapstructure:"top_k,omitempty"`

	// Chatterbox Turbo nucleus sampling threshold (ignored for Kokoro).
	// Cumulative probability cutoff for token selection.
	//
	TopP float64 `json:"top_p,omitempty" yaml:"top_p,omitempty" mapstructure:"top_p,omitempty"`

	// Voice identifier for synthesis.
	//
	// For Kokoro, use built-in voice IDs:
	// - af_heart (American Female, default)
	// - af_bella, af_nicole, af_sarah, af_sky (American Female)
	// - am_adam, am_michael (American Male)
	// - bf_emma, bf_isabella (British Female)
	// - bm_george, bm_lewis (British Male)
	//
	// For Pocket TTS, use built-in voice IDs:
	// - alba (default), marius, javert, jean
	// - fantine, cosette, eponine, azelma
	//
	// For Chatterbox Turbo, use a voice profile name defined in voice_profiles.
	//
	Voice string `json:"voice,omitempty" yaml:"voice,omitempty" mapstructure:"voice,omitempty"`

	// Named voice profiles for voice cloning (Chatterbox Turbo only).
	// Each profile maps a name to a reference audio file (~10s of speech).
	//
	VoiceProfiles LlamaFarmConfigVoiceTtsVoiceProfiles `json:"voice_profiles,omitempty" yaml:"voice_profiles,omitempty" mapstructure:"voice_profiles,omitempty"`
}

// Named voice profiles for voice cloning (Chatterbox Turbo only).
// Each profile maps a name to a reference audio file (~10s of speech).
type LlamaFarmConfigVoiceTtsVoiceProfiles map[string]struct {
	// Path to reference audio file for voice cloning.
	// Can be relative to project directory or absolute.
	//
	AudioPath string `json:"audio_path" yaml:"audio_path" mapstructure:"audio_path"`

	// Human-readable description of this voice
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigVoiceTts) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain LlamaFarmConfigVoiceTts
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["keep_loaded"]; !ok || v == nil {
		plain.KeepLoaded = false
	}
	if v, ok := raw["model"]; !ok || v == nil {
		plain.Model = "kokoro"
	}
	if v, ok := raw["repetition_penalty"]; !ok || v == nil {
		plain.RepetitionPenalty = 1.2
	}
	if 2 < plain.RepetitionPenalty {
		return fmt.Errorf("field %s: must be <= %v", "repetition_penalty", 2)
	}
	if 1 > plain.RepetitionPenalty {
		return fmt.Errorf("field %s: must be >= %v", "repetition_penalty", 1)
	}
	if v, ok := raw["speed"]; !ok || v == nil {
		plain.Speed = 0.95
	}
	if 2 < plain.Speed {
		return fmt.Errorf("field %s: must be <= %v", "speed", 2)
	}
	if 0.5 > plain.Speed {
		return fmt.Errorf("field %s: must be >= %v", "speed", 0.5)
	}
	if v, ok := raw["temperature"]; !ok || v == nil {
		plain.Temperature = 0.8
	}
	if 2 < plain.Temperature {
		return fmt.Errorf("field %s: must be <= %v", "temperature", 2)
	}
	if 0.1 > plain.Temperature {
		return fmt.Errorf("field %s: must be >= %v", "temperature", 0.1)
	}
	if v, ok := raw["top_k"]; !ok || v == nil {
		plain.TopK = 1000.0
	}
	if 5000 < plain.TopK {
		return fmt.Errorf("field %s: must be <= %v", "top_k", 5000)
	}
	if 1 > plain.TopK {
		return fmt.Errorf("field %s: must be >= %v", "top_k", 1)
	}
	if v, ok := raw["top_p"]; !ok || v == nil {
		plain.TopP = 0.95
	}
	if 1 < plain.TopP {
		return fmt.Errorf("field %s: must be <= %v", "top_p", 1)
	}
	if 0 > plain.TopP {
		return fmt.Errorf("field %s: must be >= %v", "top_p", 0)
	}
	if v, ok := raw["voice"]; !ok || v == nil {
		plain.Voice = "af_heart"
	}
	*j = LlamaFarmConfigVoiceTts(plain)
	return nil
}

// End-of-turn detection configuration. Controls how the system detects
// when a user has finished speaking vs when they're just pausing to think.
// This prevents the LLM from responding prematurely during thinking pauses.
type LlamaFarmConfigVoiceTurnDetection struct {
	// Base silence duration for complete utterances (seconds).
	// Used when the transcription appears linguistically complete
	// (ends with punctuation or a complete phrase like "yes", "thanks").
	//
	BaseSilenceDuration float64 `json:"base_silence_duration,omitempty" yaml:"base_silence_duration,omitempty" mapstructure:"base_silence_duration,omitempty"`

	// Enable smart end-of-turn detection using linguistic analysis.
	// When enabled, the system analyzes partial transcriptions to detect
	// thinking pauses vs actual end of utterance, preventing premature
	// LLM responses. When disabled, uses fixed silence threshold only.
	//
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Maximum silence before forcing end-of-turn (seconds).
	// Even if the utterance seems incomplete, processing starts after
	// this timeout to ensure responsiveness.
	//
	MaxSilenceDuration float64 `json:"max_silence_duration,omitempty" yaml:"max_silence_duration,omitempty" mapstructure:"max_silence_duration,omitempty"`

	// Extended silence duration for incomplete utterances (seconds).
	// Used when linguistic analysis suggests the user is mid-thought
	// (trailing conjunctions like "and", "but", prepositions like "to",
	// "with", or filler words like "um", "uh").
	//
	ThinkingSilenceDuration float64 `json:"thinking_silence_duration,omitempty" yaml:"thinking_silence_duration,omitempty" mapstructure:"thinking_silence_duration,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigVoiceTurnDetection) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain LlamaFarmConfigVoiceTurnDetection
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["base_silence_duration"]; !ok || v == nil {
		plain.BaseSilenceDuration = 0.4
	}
	if 2 < plain.BaseSilenceDuration {
		return fmt.Errorf("field %s: must be <= %v", "base_silence_duration", 2)
	}
	if 0.1 > plain.BaseSilenceDuration {
		return fmt.Errorf("field %s: must be >= %v", "base_silence_duration", 0.1)
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = true
	}
	if v, ok := raw["max_silence_duration"]; !ok || v == nil {
		plain.MaxSilenceDuration = 2.5
	}
	if 10 < plain.MaxSilenceDuration {
		return fmt.Errorf("field %s: must be <= %v", "max_silence_duration", 10)
	}
	if 0.5 > plain.MaxSilenceDuration {
		return fmt.Errorf("field %s: must be >= %v", "max_silence_duration", 0.5)
	}
	if v, ok := raw["thinking_silence_duration"]; !ok || v == nil {
		plain.ThinkingSilenceDuration = 1.2
	}
	if 5 < plain.ThinkingSilenceDuration {
		return fmt.Errorf("field %s: must be <= %v", "thinking_silence_duration", 5)
	}
	if 0.3 > plain.ThinkingSilenceDuration {
		return fmt.Errorf("field %s: must be >= %v", "thinking_silence_duration", 0.3)
	}
	*j = LlamaFarmConfigVoiceTurnDetection(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfigVoice) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain LlamaFarmConfigVoice
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["enable_thinking"]; !ok || v == nil {
		plain.EnableThinking = false
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = true
	}
	*j = LlamaFarmConfigVoice(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LlamaFarmConfig) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in LlamaFarmConfig: required")
	}
	if _, ok := raw["namespace"]; raw != nil && !ok {
		return fmt.Errorf("field namespace in LlamaFarmConfig: required")
	}
	if _, ok := raw["runtime"]; raw != nil && !ok {
		return fmt.Errorf("field runtime in LlamaFarmConfig: required")
	}
	type Plain LlamaFarmConfig
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["datasets"]; !ok || v == nil {
		plain.Datasets = []LlamaFarmConfigDatasetsElem{}
	}
	if v, ok := raw["prompts"]; !ok || v == nil {
		plain.Prompts = []PromptSet{}
	}
	if v, ok := raw["version"]; !ok || v == nil {
		plain.Version = "v1"
	}
	*j = LlamaFarmConfig(plain)
	return nil
}

type PromptMessage struct {
	// Message content
	Content string `json:"content" yaml:"content" mapstructure:"content"`

	// Message role (e.g., "system", "user", "assistant", "tool")
	Role string `json:"role" yaml:"role" mapstructure:"role"`

	// Tool call ID
	ToolCallId *string `json:"tool_call_id,omitempty" yaml:"tool_call_id,omitempty" mapstructure:"tool_call_id,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PromptMessage) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["content"]; raw != nil && !ok {
		return fmt.Errorf("field content in PromptMessage: required")
	}
	if _, ok := raw["role"]; raw != nil && !ok {
		return fmt.Errorf("field role in PromptMessage: required")
	}
	type Plain PromptMessage
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PromptMessage(plain)
	return nil
}

type PromptSet struct {
	// List of messages in this prompt set
	Messages []PromptMessage `json:"messages" yaml:"messages" mapstructure:"messages"`

	// Unique prompt set identifier
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PromptSet) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in PromptSet: required")
	}
	type Plain PromptSet
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["messages"]; !ok || v == nil {
		plain.Messages = []PromptMessage{}
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9_]*$`, string(plain.Name)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Name", `^[a-z][a-z0-9_]*$`)
	}
	*j = PromptSet(plain)
	return nil
}

// Schema for RAG system strategy configurations
type RAGStrategyConfigurationSchema struct {
	// Processing pipelines for parsers and extractors. If empty or not specified, the
	// built-in 'universal_rag' strategy is used automatically.
	DataProcessingStrategies []LlamaFarmConfigRagDataProcessingStrategiesElem `json:"data_processing_strategies,omitempty" yaml:"data_processing_strategies,omitempty" mapstructure:"data_processing_strategies,omitempty"`

	// Independent database definitions with their own embedding/retrieval strategies
	Databases []LlamaFarmConfigRagDatabasesElem `json:"databases,omitempty" yaml:"databases,omitempty" mapstructure:"databases,omitempty"`

	// Name of the default database to use for RAG queries. If not specified, uses the
	// first database in the databases array.
	DefaultDatabase *string `json:"default_database,omitempty" yaml:"default_database,omitempty" mapstructure:"default_database,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RAGStrategyConfigurationSchema) UnmarshalJSON(value []byte) error {
	type Plain RAGStrategyConfigurationSchema
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Databases != nil && len(plain.Databases) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "databases", 1)
	}
	if plain.DefaultDatabase != nil {
		if matched, _ := regexp.MatchString(`^[a-z][a-z0-9_]*$`, string(*plain.DefaultDatabase)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "DefaultDatabase", `^[a-z][a-z0-9_]*$`)
		}
	}
	*j = RAGStrategyConfigurationSchema(plain)
	return nil
}

type Tool struct {
	// Description of the tool
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Name of the tool
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Parameters of the tool
	Parameters ToolParameters `json:"parameters" yaml:"parameters" mapstructure:"parameters"`

	// Type of tool
	Type ToolType `json:"type" yaml:"type" mapstructure:"type"`
}

// Parameters of the tool
type ToolParameters map[string]interface{}

type ToolType string

const ToolTypeFunction ToolType = "function"

var enumValues_ToolType = []interface{}{
	"function",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ToolType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ToolType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ToolType, v)
	}
	*j = ToolType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Tool) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in Tool: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Tool: required")
	}
	if _, ok := raw["parameters"]; raw != nil && !ok {
		return fmt.Errorf("field parameters in Tool: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Tool: required")
	}
	type Plain Tool
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Tool(plain)
	return nil
}
