name: "Context-Aware Prompt Selection"

prompts:
  strategy: "context_aware"
  config:
    context_factors:
      document_type: 0.3
      user_expertise: 0.25
      query_complexity: 0.2
      response_requirements: 0.15
      system_load: 0.1
    
    selection_rules:
      expert_technical:
        conditions:
          user_expertise: "expert"
          document_type: "technical"
        template: "technical_expert_analysis"
      
      general_simple:
        conditions:
          user_expertise: "general"
          query_complexity: "low"
        template: "simple_explanation"
    
    fallback_chain:
      - "qa_detailed"
      - "qa_basic"