name: "Performance-Optimized Prompt System"

prompts:
  strategy: "performance_optimized"
  config:
    optimization_target: "speed"
    constraints:
      max_tokens: 2000
      max_latency_ms: 1000
      min_quality_score: 0.8
    
    template_performance_profiles:
      qa_fast:
        avg_tokens: 500
        avg_latency_ms: 200
        quality_score: 0.8
      qa_balanced:
        avg_tokens: 1000
        avg_latency_ms: 500
        quality_score: 0.85
    
    load_balancing:
      high_load: "qa_fast"
      medium_load: "qa_balanced"
      low_load: "qa_detailed"