name: "Prompt Strategy A/B Test"

prompts:
  strategy: "ab_testing"
  config:
    ab_testing:
      test_name: "selection_strategy_comparison"
      variants:
        rule_based:
          strategy: "rule_based"
          config:
            rules:
              - condition: "document_type == 'technical'"
                template: "technical_analysis"
        context_aware:
          strategy: "context_aware"
          config:
            context_factors:
              document_type: 0.4
              user_expertise: 0.3
              query_complexity: 0.3