name: "Template A/B Test Configuration"

prompts:
  strategy: "ab_testing"
  config:
    ab_testing:
      enabled: true
      test_name: "qa_template_optimization"
      duration_days: 14
      traffic_split: 0.5
      
      variants:
        control:
          template: "qa_basic"
          description: "Current basic Q&A template"
        treatment:
          template: "qa_enhanced"
          description: "Enhanced Q&A with reasoning steps"
      
      success_metrics:
        - "user_satisfaction"
        - "response_relevance"
        - "task_completion_rate"
      
      monitoring:
        track_user_feedback: true
        measure_response_quality: true
        monitor_system_performance: true

  templates:
    qa_enhanced:
      template: |
        Context: {context}
        
        Question: {question}
        
        Let me analyze this step by step:
        1. Key information from context:
        2. Direct answer:
        3. Supporting details:
        
        Final Answer:
      metadata:
        variant: "treatment"
        approach: "structured_reasoning"