# generated by datamodel-codegen:
#   filename:  schema.deref.yaml
#   timestamp: 2025-09-29T16:35:44+00:00

from __future__ import annotations
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field, conint, constr


class Version(Enum):
    v1 = "v1"


class Prompt(BaseModel):
    role: Optional[str] = Field(
        None, description='Prompt role (e.g., "system", "user", "assistant")'
    )
    content: str = Field(..., description='Prompt content (e.g., "You are a helpful assistant.")')


class Type(Enum):
    ChromaStore = "ChromaStore"
    QdrantStore = "QdrantStore"


class Type1(Enum):
    HuggingFaceEmbedder = "HuggingFaceEmbedder"
    OllamaEmbedder = "OllamaEmbedder"
    OpenAIEmbedder = "OpenAIEmbedder"
    SentenceTransformerEmbedder = "SentenceTransformerEmbedder"


class EmbeddingStrategy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="Strategy identifier")
    type: Type1 = Field(..., description="Embedding type")
    config: Optional[dict[str, Any]] = Field(None, description="Embedder configuration")
    condition: Optional[str] = Field(
        None,
        description="Optional condition for when to use this embedding (e.g., doc.type == 'code')",
    )
    priority: Optional[int] = Field(0, description="Priority for automatic selection")


class Type2(Enum):
    VectorRetriever = "VectorRetriever"
    HybridRetriever = "HybridRetriever"
    BM25Retriever = "BM25Retriever"
    RerankedRetriever = "RerankedRetriever"
    GraphRetriever = "GraphRetriever"
    ElasticRetriever = "ElasticRetriever"
    BasicSimilarityStrategy = "BasicSimilarityStrategy"
    MetadataFilteredStrategy = "MetadataFilteredStrategy"
    MultiQueryStrategy = "MultiQueryStrategy"
    RerankedStrategy = "RerankedStrategy"
    HybridUniversalStrategy = "HybridUniversalStrategy"


class RetrievalStrategy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="Strategy identifier")
    type: Type2 = Field(..., description="Retrieval type")
    config: Optional[dict[str, Any]] = Field(None, description="Retrieval configuration")
    default: Optional[bool] = Field(False, description="Whether this is the default strategy")


class Database(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]*$", min_length=1, max_length=50) = Field(
        ..., description="Unique database identifier"
    )
    type: Type = Field(
        ..., description="Database type (accepts both short names and Store class names)"
    )
    config: Optional[dict[str, Any]] = Field(None, description="Database-specific configuration")
    embedding_strategies: Optional[list[EmbeddingStrategy]] = Field(
        None,
        description="Multiple embedding strategies for hybrid search",
        title="Embedding Strategies",
    )
    retrieval_strategies: Optional[list[RetrievalStrategy]] = Field(
        None,
        description="Multiple retrieval strategies for different query patterns",
        title="Retrieval Strategies",
    )
    default_embedding_strategy: Optional[str] = Field(
        None, description="Name of the default embedding strategy to use"
    )
    default_retrieval_strategy: Optional[str] = Field(
        None, description="Name of the default retrieval strategy to use"
    )


class Type3(Enum):
    CSVParser_LlamaIndex = "CSVParser_LlamaIndex"
    CSVParser_Pandas = "CSVParser_Pandas"
    CSVParser_Python = "CSVParser_Python"
    DirectoryParser = "DirectoryParser"
    DocxParser_LlamaIndex = "DocxParser_LlamaIndex"
    DocxParser_PythonDocx = "DocxParser_PythonDocx"
    ExcelParser_LlamaIndex = "ExcelParser_LlamaIndex"
    ExcelParser_OpenPyXL = "ExcelParser_OpenPyXL"
    ExcelParser_Pandas = "ExcelParser_Pandas"
    MarkdownParser_LlamaIndex = "MarkdownParser_LlamaIndex"
    MarkdownParser_Python = "MarkdownParser_Python"
    PDFParser_LlamaIndex = "PDFParser_LlamaIndex"
    PDFParser_PyPDF2 = "PDFParser_PyPDF2"
    TextParser_LlamaIndex = "TextParser_LlamaIndex"
    TextParser_Python = "TextParser_Python"


class Parser(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Optional[Type3] = Field(None, description="Parser type")
    config: Optional[dict[str, Any]] = Field(None, description="Parser configuration")
    file_extensions: Optional[list[constr(pattern=r"^\.[a-zA-Z0-9]+$")]] = Field(
        None,
        description='File extensions this parser handles (e.g., [".pdf", ".PDF"])',
        examples=[[".pdf", ".PDF"], [".csv", ".tsv"], [".md", ".markdown"]],
    )
    file_include_patterns: Optional[list[str]] = Field(
        None,
        description='Glob patterns for files to include (e.g., ["*.pdf", "report_*.pdf"])',
        examples=[["*.pdf", "*.PDF"], ["report_*.csv"], ["README*", "*.md"]],
    )
    priority: Optional[int] = Field(0, description="Priority for automatic selection")
    fallback_parser: Optional[str] = Field(None, description="Parser to use if this one fails")


class Extractor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str = Field(..., description="Extractor type")
    config: Optional[dict[str, Any]] = Field(None, description="Extractor configuration")
    required_for: Optional[list[str]] = Field(
        None, description="Database names that require this extractor"
    )
    condition: Optional[str] = Field(
        None, description="Optional condition for when to use this extractor"
    )
    file_include_patterns: Optional[list[str]] = Field(
        None,
        description="Glob patterns for files to apply this extractor to",
        examples=[["*.pdf", "*.PDF"], ["*"]],
    )
    priority: Optional[conint(ge=0, le=1000)] = Field(
        50, description="Extractor priority (higher = apply first)"
    )


class DataProcessingStrategy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]*$", min_length=1, max_length=50) = Field(
        ..., description="Unique strategy identifier"
    )
    description: Optional[constr(min_length=10, max_length=500)] = Field(
        None, description="Strategy description"
    )
    parsers: list[Parser] = Field(
        ..., description="Document parsers in processing order", min_length=1, title="Parsers"
    )
    extractors: Optional[list[Extractor]] = Field(
        None, description="Metadata and feature extractors", title="Extractors"
    )


class Rag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    databases: Optional[list[Database]] = Field(
        None,
        description="Independent database definitions with their own embedding/retrieval strategies",
        min_length=1,
        title="Database Configurations",
    )
    data_processing_strategies: Optional[list[DataProcessingStrategy]] = Field(
        None,
        description="Processing pipelines for parsers and extractors",
        min_length=1,
        title="Data Processing Strategies",
    )


class Dataset(BaseModel):
    name: str = Field(..., description="Dataset name")
    data_processing_strategy: str = Field(
        ..., description="RAG data processing strategy to use for the dataset"
    )
    database: str = Field(..., description="RAG database to use for the dataset")
    files: list[str] = Field(..., description="List of file hashes")


class Provider(Enum):
    openai = "openai"
    ollama = "ollama"


class Runtime(BaseModel):
    provider: Provider
    model: str = Field(..., description="Model name or ID")
    base_url: Optional[str] = Field(None, description="Base URL for the provider")
    api_key: Optional[str] = Field(
        None, description="API key for the provider (optional, not required for Ollama)"
    )
    instructor_mode: Optional[str] = Field(
        None,
        description="Instructor mode to use for structured output (e.g., tools, json, md_json, anthropic_tools, gemini_json, etc.)",
    )
    model_api_parameters: Optional[Any] = Field(
        None, description="Additional parameters passed to the API provider"
    )


class LlamaFarmConfig(BaseModel):
    version: Version = Field(..., description='Config version, must be "v1"')
    name: str = Field(..., description="Project name", examples=["my-project"])
    namespace: str = Field(..., description="Project namespace", examples=["my-namespace"])
    prompts: Optional[list[Prompt]] = []
    rag: Optional[Rag] = Field(
        None,
        description="Schema for RAG system strategy configurations",
        title="RAG Strategy Configuration Schema",
    )
    datasets: Optional[list[Dataset]] = Field([], description="List of dataset configurations")
    runtime: Runtime
