# generated by datamodel-codegen:
#   filename:  schema.deref.yaml
#   timestamp: 2025-09-24T00:56:42+00:00

from __future__ import annotations
from enum import Enum
from typing import Any, Optional
from pydantic import AnyUrl, BaseModel, ConfigDict, Field, confloat, conint, constr, model_validator


class Version(Enum):
    v1 = "v1"


class Prompt(BaseModel):
    role: Optional[str] = Field(
        None, description='Prompt role (e.g., "system", "user", "assistant")'
    )
    content: str = Field(..., description='Prompt content (e.g., "You are a helpful assistant.")')


class Type(Enum):
    ChromaStore = "ChromaStore"
    QdrantStore = "QdrantStore"


class Type1(Enum):
    HuggingFaceEmbedder = "HuggingFaceEmbedder"
    OllamaEmbedder = "OllamaEmbedder"
    OpenAIEmbedder = "OpenAIEmbedder"
    SentenceTransformerEmbedder = "SentenceTransformerEmbedder"


class EmbeddingStrategy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="Strategy identifier")
    type: Type1 = Field(..., description="Embedding type")
    config: Optional[dict[str, Any]] = Field(None, description="Embedder configuration")
    condition: Optional[str] = Field(
        None,
        description="Optional condition for when to use this embedding (e.g., doc.type == 'code')",
    )
    priority: Optional[int] = Field(0, description="Priority for automatic selection")


class Type2(Enum):
    VectorRetriever = "VectorRetriever"
    HybridRetriever = "HybridRetriever"
    BM25Retriever = "BM25Retriever"
    RerankedRetriever = "RerankedRetriever"
    GraphRetriever = "GraphRetriever"
    ElasticRetriever = "ElasticRetriever"
    BasicSimilarityStrategy = "BasicSimilarityStrategy"
    MetadataFilteredStrategy = "MetadataFilteredStrategy"
    MultiQueryStrategy = "MultiQueryStrategy"
    RerankedStrategy = "RerankedStrategy"
    HybridUniversalStrategy = "HybridUniversalStrategy"


class RetrievalStrategy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., description="Strategy identifier")
    type: Type2 = Field(..., description="Retrieval type")
    config: Optional[dict[str, Any]] = Field(None, description="Retrieval configuration")
    default: Optional[bool] = Field(False, description="Whether this is the default strategy")


class Database(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]*$", min_length=1, max_length=50) = Field(
        ..., description="Unique database identifier"
    )
    type: Type = Field(
        ..., description="Database type (accepts both short names and Store class names)"
    )
    config: Optional[dict[str, Any]] = Field(None, description="Database-specific configuration")
    embedding_strategies: Optional[list[EmbeddingStrategy]] = Field(
        None,
        description="Multiple embedding strategies for hybrid search",
        title="Embedding Strategies",
    )
    retrieval_strategies: Optional[list[RetrievalStrategy]] = Field(
        None,
        description="Multiple retrieval strategies for different query patterns",
        title="Retrieval Strategies",
    )
    default_embedding_strategy: Optional[str] = Field(
        None, description="Name of the default embedding strategy to use"
    )
    default_retrieval_strategy: Optional[str] = Field(
        None, description="Name of the default retrieval strategy to use"
    )


class Type3(Enum):
    CSVParser_LlamaIndex = "CSVParser_LlamaIndex"
    CSVParser_Pandas = "CSVParser_Pandas"
    CSVParser_Python = "CSVParser_Python"
    DirectoryParser = "DirectoryParser"
    DocxParser_LlamaIndex = "DocxParser_LlamaIndex"
    DocxParser_PythonDocx = "DocxParser_PythonDocx"
    ExcelParser_LlamaIndex = "ExcelParser_LlamaIndex"
    ExcelParser_OpenPyXL = "ExcelParser_OpenPyXL"
    ExcelParser_Pandas = "ExcelParser_Pandas"
    MarkdownParser_LlamaIndex = "MarkdownParser_LlamaIndex"
    MarkdownParser_Python = "MarkdownParser_Python"
    PDFParser_LlamaIndex = "PDFParser_LlamaIndex"
    PDFParser_PyPDF2 = "PDFParser_PyPDF2"
    TextParser_LlamaIndex = "TextParser_LlamaIndex"
    TextParser_Python = "TextParser_Python"


class Parser(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Optional[Type3] = Field(None, description="Parser type")
    config: Optional[dict[str, Any]] = Field(None, description="Parser configuration")
    file_extensions: Optional[list[constr(pattern=r"^\.[a-zA-Z0-9]+$")]] = Field(
        None,
        description='File extensions this parser handles (e.g., [".pdf", ".PDF"])',
        examples=[[".pdf", ".PDF"], [".csv", ".tsv"], [".md", ".markdown"]],
    )
    file_include_patterns: Optional[list[str]] = Field(
        None,
        description='Glob patterns for files to include (e.g., ["*.pdf", "report_*.pdf"])',
        examples=[["*.pdf", "*.PDF"], ["report_*.csv"], ["README*", "*.md"]],
    )
    file_exclude_patterns: Optional[list[str]] = Field(
        None,
        description='Glob patterns for files to exclude (e.g., ["*_draft.pdf", "*.tmp"])',
        examples=[["*_draft.pdf", "*.tmp.pdf"], ["~$*", "*.bak"]],
    )
    priority: Optional[int] = Field(0, description="Priority for automatic selection")
    mime_types: Optional[list[str]] = Field(
        None,
        description='MIME types this parser handles (e.g., ["application/pdf"])',
        examples=[
            ["application/pdf"],
            ["text/csv", "text/tab-separated-values"],
            ["text/markdown", "text/x-markdown"],
        ],
    )
    fallback_parser: Optional[str] = Field(None, description="Parser to use if this one fails")


class Extractor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str = Field(..., description="Extractor type")
    config: Optional[dict[str, Any]] = Field(None, description="Extractor configuration")
    required_for: Optional[list[str]] = Field(
        None, description="Database names that require this extractor"
    )
    condition: Optional[str] = Field(
        None, description="Optional condition for when to use this extractor"
    )
    file_include_patterns: Optional[list[str]] = Field(
        None,
        description="Glob patterns for files to apply this extractor to",
        examples=[["*.pdf", "*.PDF"], ["*"]],
    )
    file_exclude_patterns: Optional[list[str]] = Field(
        None,
        description="Glob patterns for files to exclude from this extractor",
        examples=[["*.tmp", "*.bak"]],
    )
    priority: Optional[conint(ge=0, le=1000)] = Field(
        50, description="Extractor priority (higher = apply first)"
    )


class DataProcessingStrategy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9_]*$", min_length=1, max_length=50) = Field(
        ..., description="Unique strategy identifier"
    )
    description: Optional[constr(min_length=10, max_length=500)] = Field(
        None, description="Strategy description"
    )
    parsers: list[Parser] = Field(
        ..., description="Document parsers in processing order", min_length=1, title="Parsers"
    )
    extractors: Optional[list[Extractor]] = Field(
        None, description="Metadata and feature extractors", title="Extractors"
    )


class Rag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    databases: Optional[list[Database]] = Field(
        None,
        description="Independent database definitions with their own embedding/retrieval strategies",
        min_length=1,
        title="Database Configurations",
    )
    data_processing_strategies: Optional[list[DataProcessingStrategy]] = Field(
        None,
        description="Processing pipelines for parsers and extractors",
        min_length=1,
        title="Data Processing Strategies",
    )


class Provider(Enum):
    openai = "openai"
    ollama = "ollama"
    anthropic = "anthropic"


class InstructorMode(Enum):
    json = "json"
    markdown = "markdown"
    text = "text"


class Parameters(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    temperature: Optional[confloat(ge=0.0, le=2.0)] = Field(0.7, description="Sampling temperature")
    top_p: Optional[confloat(ge=0.0, le=1.0)] = Field(None, description="Top-p sampling parameter")
    top_k: Optional[conint(ge=1)] = Field(None, description="Top-k sampling parameter")
    max_tokens: Optional[conint(ge=1)] = Field(None, description="Maximum tokens to generate")
    presence_penalty: Optional[confloat(ge=-2.0, le=2.0)] = Field(
        None, description="Presence penalty"
    )
    frequency_penalty: Optional[confloat(ge=-2.0, le=2.0)] = Field(
        None, description="Frequency penalty"
    )
    seed: Optional[int] = Field(None, description="Random seed for deterministic generation")


class RuntimeModel(BaseModel):
    name: constr(pattern=r"^[a-z0-9][a-z0-9-_]*$") = Field(
        ..., description="Unique model configuration name"
    )
    provider: Provider = Field(..., description="Model provider")
    model: str = Field(..., description="Model identifier (e.g., llama3.1:8b, gpt-4, claude-3)")
    base_url: Optional[AnyUrl] = Field(None, description="API base URL for the provider")
    api_key: Optional[str] = Field(None, description="API key (if required by provider)")
    instructor_mode: Optional[InstructorMode] = Field(
        "json", description="Instructor mode for structured output"
    )
    parameters: Optional[Parameters] = Field(None, description="Model-specific parameters")


class Dataset(BaseModel):
    name: str = Field(..., description="Dataset name")
    data_processing_strategy: str = Field(
        ..., description="RAG data processing strategy to use for the dataset"
    )
    database: str = Field(..., description="RAG database to use for the dataset")
    files: list[str] = Field(..., description="List of file hashes")


# Provider1 is deprecated - use Provider instead
# Keeping for backward compatibility but using the same Provider enum

class Runtime(BaseModel):
    provider: Provider  # Using main Provider enum instead of duplicate Provider1
    model: str = Field(..., description="Model name or ID")
    base_url: Optional[str] = Field(None, description="Base URL for the provider")
    api_key: Optional[str] = Field(None, description="API key for the provider")
    instructor_mode: Optional[str] = Field(
        None, description="Instructor mode to use for the provider"
    )
    model_api_parameters: Optional[Any] = Field(
        None, description="Additional parameters passed to the API provider"
    )


class LlamaFarmConfig(BaseModel):
    version: Version = Field(..., description='Config version, must be "v1"')
    name: str = Field(..., description="Project name", examples=["my-project"])
    namespace: str = Field(..., description="Project namespace", examples=["my-namespace"])
    prompts: Optional[list[Prompt]] = []
    rag: Optional[Rag] = Field(
        None,
        description="Schema for RAG system strategy configurations",
        title="RAG Strategy Configuration Schema",
    )
    default_model: Optional[constr(pattern=r"^[a-z0-9][a-z0-9-_]*$")] = Field(
        None, description="Name of the default model to use"
    )
    runtime_models: Optional[list[RuntimeModel]] = Field(
        None, description="Named model configurations for runtime use", min_length=1
    )
    datasets: Optional[list[Dataset]] = Field([], description="List of dataset configurations")
    runtime: Optional[Runtime] = Field(
        None,
        description="DEPRECATED: Use runtime_models for multi-model support. This field will be removed in v2.0",
    )
    
    @model_validator(mode='after')
    def validate_runtime_configuration(self):
        """Validate that either runtime_models or runtime is set, but not both."""
        if self.runtime and self.runtime_models:
            raise ValueError(
                "Both 'runtime' and 'runtime_models' are set. Please migrate to 'runtime_models' "
                "and remove 'runtime' configuration. The 'runtime' field is deprecated."
            )
        if not self.runtime and not self.runtime_models:
            raise ValueError(
                "No runtime configuration found. Please add 'runtime_models' configuration. "
                "Example:\n"
                "runtime_models:\n"
                "  - name: primary\n"
                "    provider: ollama\n"
                "    model: llama3.1:8b\n"
                "    base_url: http://localhost:11434/v1\n"
                "    instructor_mode: json"
            )
        return self
