$schema: "http://json-schema.org/draft-07/schema#"
title: LlamaFarm Config
type: object
required:
  - version
  - name
  - namespace
  - prompts
  - rag
  - datasets
  - runtime
properties:
  version:
    type: string
    enum: ["v1"]
    default: v1
    description: Config version, must be "v1"
  name:
    type: string
    description: Project name
    example: my-project
  namespace:
    type: string
    description: Project namespace
    example: my-namespace
  prompts:
    type: array
    items:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Prompt name
        sections:
          type: array
          description: List of prompt sections
          items:
            type: object
            required:
              - title
              - content
            properties:
              title:
                type: string
                description: Section title
              content:
                type: array
                description: List of section content
                items:
                  type: string
                  description: Section content
        raw_text:
          type: string
          description: Raw text of the prompt
      example:
        name: default
        sections:
          - title: "IDENTITY and PURPOSE"
            content:
              - "You are a helpful assistant that can answer questions and help with tasks."
    default: []

  rag:
    $ref: "../rag/schema.yaml"

  datasets:
    type: array
    description: List of dataset configurations
    items:
      type: object
      required:
        - name
        - files
      properties:
        name:
          type: string
          description: Dataset name
        rag_strategy:
          type: string
          description: RAG strategy to use for the dataset
          default: auto
        files:
          type: array
          description: List of file hashes
          items:
            type: string
            description: sha256 of the file content (e.g., "2b3e321d021e5c625a4a003f0624801fa46faab59b530caddcd65a5c106b8a17")
          default: []
    default: []

  runtime:
    type: object
    required:
      - provider
      - model
    properties:
      provider:
        type: string
        enum: [openai, ollama]
        default: openai
      model:
        type: string
        description: Model name or ID
      base_url:
        type: string
        description: Base URL for the provider
      api_key:
        type: string
        description: API key for the provider
      model_api_parameters:
        description: Additional parameters passed to the API provider
        additionalProperties: true
