{
  "name": "Multi-Provider Configuration",
  "version": "1.0.0",
  "default_provider": "openai_gpt4",
  "fallback_chain": [
    "openai_gpt4",
    "anthropic_claude",
    "local_llama"
  ],
  "providers": {
    "openai_gpt4": {
      "type": "cloud",
      "provider": "openai",
      "model": "gpt-4-turbo-preview",
      "api_key": "${OPENAI_API_KEY}",
      "base_url": "https://api.openai.com/v1",
      "max_tokens": 4096,
      "temperature": 0.7
    },
    "anthropic_claude": {
      "type": "cloud",
      "provider": "anthropic",
      "model": "claude-3-opus-20240229",
      "api_key": "${ANTHROPIC_API_KEY}",
      "base_url": "https://api.anthropic.com/v1",
      "max_tokens": 4096,
      "temperature": 0.7
    },
    "local_llama": {
      "type": "local",
      "provider": "ollama",
      "model": "llama2:13b",
      "host": "localhost",
      "port": 11434,
      "timeout": 120
    }
  },
  "selection_strategy": {
    "type": "cost_optimized",
    "factors": {
      "cost": 0.4,
      "quality": 0.3,
      "speed": 0.3
    }
  }
}