# Pattern Extractor Component Schema
# JSON Schema draft-07 format
$schema: http://json-schema.org/draft-07/schema#
$id: components/extractors/pattern_extractor/schema.yaml
title: Pattern Extractor Configuration
description: Extract regex patterns
type: object
additionalProperties: false
properties:
  enabled:
    type: boolean
    default: true
    description: Enable this extractor
