/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated from rag/schema.yaml by designer/generate-types.ts
 */

// ============================================================================
// Vector Store Config Interfaces (generated by json-schema-to-typescript)
// ============================================================================

export interface ChromaStoreConfiguration {
  /**
   * Collection name
   */
  collection_name?: string;
  /**
   * Server host
   */
  host?: string | null;
  /**
   * Server port
   */
  port?: number;
  /**
   * Distance metric
   */
  distance_function?: 'cosine' | 'l2' | 'ip';
  /**
   * Alternative distance metric name
   */
  distance_metric?: 'cosine' | 'l2' | 'ip';
  /**
   * Embedding dimension
   */
  embedding_dimension?: number;
  /**
   * Enable document deduplication
   */
  enable_deduplication?: boolean;
  /**
   * Built-in embedding function
   */
  embedding_function?: string | null;
}

export interface FAISSStoreConfiguration {
  /**
   * Vector dimension
   */
  dimension: number;
  /**
   * Index type
   */
  index_type?: 'Flat' | 'IVF' | 'HNSW' | 'LSH';
  /**
   * Distance metric
   */
  metric?: 'L2' | 'IP' | 'Cosine';
  /**
   * Number of clusters (IVF)
   */
  nlist?: number;
  /**
   * Clusters to search (IVF)
   */
  nprobe?: number;
  /**
   * Enable GPU acceleration
   */
  use_gpu?: boolean;
}

export interface PineconeStoreConfiguration {
  /**
   * Pinecone API key
   */
  api_key: string;
  /**
   * Pinecone environment
   */
  environment?: string;
  /**
   * Index name
   */
  index_name: string;
  /**
   * Vector dimension
   */
  dimension: number;
  /**
   * Distance metric
   */
  metric?: 'euclidean' | 'cosine' | 'dotproduct';
  /**
   * Namespace for isolation
   */
  namespace?: string;
  /**
   * Number of replicas
   */
  replicas?: number;
}

export interface QdrantStoreConfiguration {
  /**
   * Server host
   */
  host?: string;
  /**
   * Server port
   */
  port?: number;
  /**
   * gRPC port
   */
  grpc_port?: number;
  /**
   * API key
   */
  api_key?: string | null;
  /**
   * Collection name
   */
  collection_name?: string;
  /**
   * Vector dimension
   */
  vector_size: number;
  /**
   * Distance metric
   */
  distance?: 'Cosine' | 'Euclid' | 'Dot';
  /**
   * Store vectors on disk
   */
  on_disk?: boolean;
}

// ============================================================================
// Embedder Config Interfaces (generated by json-schema-to-typescript)
// ============================================================================

export interface OllamaEmbedderConfiguration {
  /**
   * Ollama model name
   */
  model?: string;
  /**
   * Ollama API endpoint (preferred)
   */
  base_url?: string;
  /**
   * Embedding dimension
   */
  dimension?: number;
  /**
   * Batch processing size
   */
  batch_size?: number;
  /**
   * Request timeout (seconds)
   */
  timeout?: number;
  /**
   * Auto-pull missing models
   */
  auto_pull?: boolean;
}

export interface HuggingFaceEmbedderConfiguration {
  /**
   * HuggingFace model ID
   */
  model_name?: string;
  /**
   * Computation device
   */
  device?: 'cpu' | 'cuda' | 'mps' | 'auto';
  /**
   * Batch size
   */
  batch_size?: number;
  /**
   * L2 normalize embeddings
   */
  normalize_embeddings?: boolean;
  /**
   * Show progress bar
   */
  show_progress_bar?: boolean;
  /**
   * Model cache directory
   */
  cache_folder?: string | null;
}

export interface OpenAIEmbedderConfiguration {
  /**
   * OpenAI embedding model
   */
  model?: string;
  /**
   * OpenAI API key
   */
  api_key?: string;
  /**
   * OpenAI API base URL
   */
  base_url?: string | null;
  /**
   * OpenAI organization ID
   */
  organization?: string | null;
  /**
   * Batch size for API calls
   */
  batch_size?: number;
  /**
   * Maximum retry attempts
   */
  max_retries?: number;
  /**
   * Request timeout in seconds
   */
  timeout?: number;
}

export interface SentenceTransformerConfiguration {
  /**
   * Model name
   */
  model_name?: string;
  /**
   * Computation device
   */
  device?: 'cpu' | 'cuda' | 'mps';
}

// ============================================================================
// Retrieval Strategy Config Interfaces (generated by json-schema-to-typescript)
// ============================================================================

export interface BasicSimilarityConfiguration {
  /**
   * Number of results
   */
  top_k?: number;
  /**
   * Distance metric
   */
  distance_metric?: 'cosine' | 'euclidean' | 'manhattan' | 'dot';
  /**
   * Minimum similarity score
   */
  score_threshold?: number | null;
}

export interface MetadataFilteredConfiguration {
  /**
   * Number of results
   */
  top_k?: number;
  /**
   * Metadata filters
   */
  filters?: {
    [k: string]: string | number | boolean | (string | number | boolean)[];
  };
  /**
   * When to apply filters
   */
  filter_mode?: 'pre' | 'post';
  /**
   * Multiplier for post-filtering
   */
  fallback_multiplier?: number;
}

export interface MultiQueryConfiguration {
  /**
   * Number of query variations
   */
  num_queries?: number;
  /**
   * Results per query
   */
  top_k?: number;
  /**
   * Result aggregation method
   */
  aggregation_method?: 'max' | 'mean' | 'weighted' | 'reciprocal_rank';
  /**
   * Weights for each query
   */
  query_weights?: number[] | null;
}

export interface RerankedConfiguration {
  /**
   * Initial candidates
   */
  initial_k?: number;
  /**
   * Final results
   */
  final_k?: number;
  /**
   * Reranking factor weights
   */
  rerank_factors?: {
    similarity_weight?: number;
    recency_weight?: number;
    length_weight?: number;
    metadata_weight?: number;
  };
  /**
   * Normalize scores before combining
   */
  normalize_scores?: boolean;
}

export interface HybridUniversalConfiguration {
  /**
   * Sub-strategies to combine
   *
   * @minItems 2
   * @maxItems 5
   */
  strategies?:
    | [
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        },
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        }
      ]
    | [
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        },
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        },
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        }
      ]
    | [
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        },
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        },
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        },
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        }
      ]
    | [
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        },
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        },
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        },
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        },
        {
          type: 'BasicSimilarityStrategy' | 'MetadataFilteredStrategy' | 'MultiQueryStrategy' | 'RerankedStrategy';
          weight?: number;
          config?: {
            [k: string]: unknown;
          };
        }
      ];
  /**
   * Combination method
   */
  combination_method?: 'weighted_average' | 'rank_fusion' | 'score_fusion';
  /**
   * Final number of results
   */
  final_k?: number;
}

// ============================================================================
// Type Constants
// ============================================================================

export const VECTOR_STORE_TYPES = ["ChromaStore","FAISSStore","PineconeStore","QdrantStore"] as const
export type VectorStoreType = typeof VECTOR_STORE_TYPES[number]

export const EMBEDDER_TYPES = ["OllamaEmbedder","HuggingFaceEmbedder","OpenAIEmbedder","SentenceTransformerEmbedder"] as const
export type EmbedderType = typeof EMBEDDER_TYPES[number]

export const RETRIEVAL_STRATEGY_TYPES = ["VectorRetriever","HybridRetriever","BM25Retriever","RerankedRetriever","GraphRetriever","ElasticRetriever","BasicSimilarityStrategy","MetadataFilteredStrategy","MultiQueryStrategy","RerankedStrategy","HybridUniversalStrategy"] as const
export type RetrievalStrategyType = typeof RETRIEVAL_STRATEGY_TYPES[number]
