parser:
  type: "CSVParser"
  config:
    content_fields: ["title", "description"]
    metadata_fields: ["category", "status", "created_date"]
    id_field: "ticket_id"
    combine_content: true
    content_separator: "\n\n"

embedder:
  type: "OllamaEmbedder"
  config:
    model: "all-minilm"
    base_url: "http://localhost:11434"
    batch_size: 8
    timeout: 30

vector_store:
  type: "ChromaStore"
  config:
    collection_name: "custom_documents"
    persist_directory: "./custom_chroma_db"