name: "Enterprise Production Prompt System"
environment: "production"

prompts:
  strategy: "multi_tier"
  config:
    primary_strategy: "ml_driven"
    fallback_strategies:
      - "context_aware"
      - "rule_based"
      - "static"
    
    performance_monitoring:
      enabled: true
      metrics:
        - "latency"
        - "quality"
        - "cost"
        - "user_satisfaction"
      alerting:
        quality_threshold: 0.8
        latency_threshold_ms: 2000
        error_rate_threshold: 0.05
    
    security:
      input_validation: true
      output_filtering: true
      audit_logging: true
      rate_limiting:
        requests_per_minute: 1000
        requests_per_user: 100
    
    caching:
      enabled: true
      backend: "redis"
      ttl_seconds: 3600
      max_cache_size: "10GB"