#!/usr/bin/env tsx
/**
 * Generate TypeScript types from models/schema.yaml
 *
 * Loads the model catalog schema and all family YAML files,
 * then generates TypeScript interfaces and exports the catalog data.
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import yaml from 'js-yaml'
import { compile } from 'json-schema-to-typescript'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

async function main() {
  console.log('🦙 Generating model catalog types from models/schema.yaml...')

  const outputDir = join(__dirname, 'src', 'types')
  mkdirSync(outputDir, { recursive: true })

  // Load model catalog schema
  const schemaPath = join(__dirname, '..', 'models', 'schema.yaml')
  const schema = yaml.load(readFileSync(schemaPath, 'utf-8')) as any

  // Pass the full schema as context so $refs can be resolved
  const compileOptions = {
    bannerComment: '',
    style: { singleQuote: true },
    additionalProperties: false, // Prevent duplicate index signatures
    $refOptions: {
      resolve: {
        // Provide the definitions so refs can be resolved
        external: false,
      },
    },
  }

  // Wrap definitions in a temporary schema with the full definitions context
  const wrapWithDefs = (def: any) => ({
    ...def,
    definitions: schema.definitions,
  })

  // Generate ProviderConfig interface (no refs to other defs)
  const providerSchema = schema.definitions?.provider_config
  if (!providerSchema) {
    console.error('❌ No provider_config definition found in schema')
    process.exit(1)
  }

  const providerTs = await compile(providerSchema, 'ProviderConfig', compileOptions)

  // Generate ModelVariant interface (has refs to provider_config)
  const variantSchema = schema.definitions?.model_variant
  if (!variantSchema) {
    console.error('❌ No model_variant definition found in schema')
    process.exit(1)
  }

  const variantTs = await compile(wrapWithDefs(variantSchema), 'ModelVariant', compileOptions)

  // Generate ModelFamily interface (has refs to model_variant)
  const familySchema = schema.definitions?.model_family
  if (!familySchema) {
    console.error('❌ No model_family definition found in schema')
    process.exit(1)
  }

  const familyTs = await compile(wrapWithDefs(familySchema), 'ModelFamily', compileOptions)

  // Load all model family YAML files from text-generation directory
  const modelsDir = join(__dirname, '..', 'models', 'text-generation')
  const familyFiles = readdirSync(modelsDir).filter((f: string) =>
    f.endsWith('.yaml')
  )

  const allFamilies: any[] = []
  const allVariants: any[] = []

  console.log(`📂 Loading ${familyFiles.length} model families from models/text-generation/...`)

  for (const file of familyFiles) {
    try {
      const familyPath = join(modelsDir, file)
      const familyData = yaml.load(readFileSync(familyPath, 'utf-8')) as any

      if (!familyData.family_id || !familyData.variants) {
        console.warn(`⚠️  Skipping ${file}: missing family_id or variants`)
        continue
      }

      allFamilies.push(familyData)

      // Add variants with family reference
      for (const variant of familyData.variants) {
        allVariants.push({
          ...variant,
          _family_id: familyData.family_id,
          _family_name: familyData.family_name,
        })
      }

      console.log(`   ✓ ${familyData.family_id} (${familyData.variants.length} variants)`)
    } catch (err) {
      console.warn(`⚠️  Failed to load ${file}:`, err)
    }
  }

  // Generate the TypeScript file
  const modelCatalogContent = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated from models/schema.yaml and models/text-generation/*.yaml
 * Run: npm run generate-types (or ./generate-types.sh)
 */

// ============================================================================
// Type Definitions (generated by json-schema-to-typescript)
// ============================================================================

${providerTs}

${variantTs}

${familyTs}

// ============================================================================
// Catalog Data
// ============================================================================

/**
 * All model families loaded from models/text-generation/*.yaml
 * Organized by capability (currently only text-generation)
 */
export const MODEL_CATALOG = {
  'text-generation': ${JSON.stringify(allFamilies, null, 2)}
} as const

/**
 * Flattened list of all model variants across all families
 * Useful for searching/filtering
 * Note: Each variant includes _family_id and _family_name for reference
 */
export const ALL_MODEL_VARIANTS = ${JSON.stringify(allVariants, null, 2)} as const

/**
 * Provider types supported across the catalog
 */
export const PROVIDER_TYPES = ['universal', 'ollama', 'lemonade', 'openai'] as const
export type ProviderType = (typeof PROVIDER_TYPES)[number]

/**
 * Model capability categories
 */
export const CAPABILITY_CATEGORIES = [
  'text-generation',
  'image-generation',
  'image-recognition',
  'audio',
  'embedding',
] as const
export type CapabilityCategory = (typeof CAPABILITY_CATEGORIES)[number]

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Get all families for a capability
 */
export function getFamiliesByCapability(capability: CapabilityCategory): any[] {
  return (MODEL_CATALOG[capability as 'text-generation'] as unknown as any[]) || []
}

/**
 * Get a specific family by ID
 */
export function getFamilyById(familyId: string): any {
  for (const families of Object.values(MODEL_CATALOG)) {
    const found = (families as unknown as any[]).find((f: any) => f.family_id === familyId)
    if (found) return found
  }
  return undefined
}

/**
 * Get a specific variant by ID
 */
export function getVariantById(variantId: string): any {
  return ALL_MODEL_VARIANTS.find((v: any) => v.id === variantId)
}

/**
 * Search variants by query (searches id, display_name, description, use_cases)
 */
export function searchVariants(query: string): any[] {
  const lowerQuery = query.toLowerCase()
  return (ALL_MODEL_VARIANTS as unknown as any[]).filter((v: any) =>
    v.id?.toLowerCase().includes(lowerQuery) ||
    v.display_name?.toLowerCase().includes(lowerQuery) ||
    v.description?.toLowerCase().includes(lowerQuery) ||
    v.use_cases?.some((uc: string) => uc.toLowerCase().includes(lowerQuery)) ||
    v._family_name?.toLowerCase().includes(lowerQuery)
  )
}

/**
 * Get variants by provider support
 */
export function getVariantsByProvider(provider: ProviderType): any[] {
  return (ALL_MODEL_VARIANTS as unknown as any[]).filter((v: any) =>
    v.providers && Object.keys(v.providers).includes(provider)
  )
}

/**
 * Get variants by use case tag
 */
export function getVariantsByUseCase(useCase: string): any[] {
  return (ALL_MODEL_VARIANTS as unknown as any[]).filter((v: any) =>
    v.use_cases?.includes(useCase)
  )
}
`

  const outputPath = join(outputDir, 'modelCatalog.ts')
  writeFileSync(outputPath, modelCatalogContent)

  console.log(`\n✅ Generated modelCatalog.ts`)
  console.log(`   📊 ${allFamilies.length} families, ${allVariants.length} variants`)
  console.log(`   📁 ${outputPath}`)
  console.log(`\n   Import from: @/types/modelCatalog`)
}

main().catch(err => {
  console.error('❌ Error generating model catalog types:', err)
  process.exit(1)
})
