name: "Multi-Template Prompt System"

prompts:
  strategy: "rule_based"
  config:
    rules:
      - condition: "query_type == 'summary'"
        template: "document_summary"
      - condition: "query_type == 'analysis'"
        template: "detailed_analysis"
    fallback: "qa_basic"
  
  templates:
    document_summary:
      template: |
        Summarize the following document:
        {context}
        
        Provide a concise summary highlighting the key points:
      input_variables:
        - "context"
      metadata:
        use_case: "summarization"
    
    detailed_analysis:
      template: |
        Analyze the following content:
        {context}
        
        Provide a detailed analysis considering:
        1. Key themes
        2. Important insights
        3. Actionable conclusions
      input_variables:
        - "context"
      metadata:
        use_case: "analysis"