name: "Simple Q&A Pipeline with Prompts"
version: "1.0"

rag_pipeline:
  retrieval_strategy: "basic_similarity"
  retrieval_config:
    top_k: 5
    similarity_threshold: 0.7

prompts:
  enabled: true
  strategy: "static_selection"
  config:
    default_template: "qa_basic"
    fallback_template: "qa_simple"
  
  templates:
    qa_basic:
      type: "basic"
      template: |
        Based on the following context:
        {context}
        
        Answer this question: {question}
        
        Provide a clear and concise answer:
      input_variables:
        - "context"
        - "question"
      metadata:
        use_case: "general_qa"
        complexity: "low"