name: "Complete RAG Pipeline with Intelligent Prompts"
version: "2.0"

parser:
  type: "PDFParser"
  config:
    extract_metadata: true
    preserve_structure: true

embedder:
  type: "OllamaEmbedder"
  config:
    model: "nomic-embed-text"
    dimension: 768

vector_store:
  type: "ChromaStore"
  config:
    collection_name: "documents_with_prompts"
    persistence_path: "./chroma_prompts_db"

retrieval:
  strategy: "hybrid_universal"
  config:
    strategies:
      - name: "metadata_filtered"
        weight: 0.6
      - name: "reranked"
        weight: 0.4
    fusion_method: "reciprocal_rank"

prompts:
  strategy: "context_aware"
  config:
    adapt_to_retrieval: true
    use_document_metadata: true
    consider_retrieval_quality: true
    
    retrieval_quality_thresholds:
      high_quality:
        min_relevance: 0.8
        min_results: 3
        template: "confident_answer"
      medium_quality:
        min_relevance: 0.6
        template: "cautious_answer"
      low_quality:
        template: "clarifying_questions"