# Models System Schema - RAG-style configuration
# Version: 2.0.0
# Schema: draft-07
$schema: http://json-schema.org/draft-07/schema#

title: Models System Configuration Schema
description: Comprehensive schema for model management, fine-tuning, and deployment strategies
version: 2.0.0

type: object
properties:
  # =====================================
  # STRATEGIES - Top-level strategy definitions
  # =====================================
  strategies:
    type: object
    description: Named strategy configurations combining components for specific use cases
    additionalProperties:
      type: object
      required: [name, description, components]
      properties:
        name:
          type: string
          description: Human-readable strategy name
          
        description:
          type: string
          description: Detailed description of strategy purpose and use case
          
        components:
          type: object
          description: Component configuration for this strategy
          properties:
            cloud_api:
              type: object
              properties:
                type:
                  type: string
                  enum: [openai_compatible, anthropic, custom]
                config:
                  type: object
                  
            model_app:
              type: object
              properties:
                type:
                  type: string
                  enum: [ollama, llamacpp, vllm, custom]
                config:
                  type: object
                  
            fine_tuner:
              type: object
              properties:
                type:
                  type: string
                  enum: [pytorch, llamafactory, custom]
                config:
                  type: object
                  
            repository:
              type: object
              properties:
                type:
                  type: string
                  enum: [huggingface, modelscope, custom]
                config:
                  type: object
                  
        fallback_chain:
          type: array
          description: Ordered list of fallback options
          items:
            type: object
            properties:
              name:
                type: string
              type:
                type: string
              config:
                type: object
                
        routing_rules:
          type: array
          description: Conditional routing based on input characteristics
          items:
            type: object
            properties:
              condition:
                type: string
              target:
                type: string
              priority:
                type: string
                enum: [low, normal, high, critical]
                
        optimization:
          type: object
          description: Performance optimization settings
          properties:
            cache_enabled:
              type: boolean
              default: true
            batch_size:
              type: integer
              minimum: 1
            timeout_seconds:
              type: integer
              minimum: 1
            retry_policy:
              type: object
              properties:
                max_attempts:
                  type: integer
                  minimum: 1
                backoff_multiplier:
                  type: number
                  minimum: 1.0
                  
        monitoring:
          type: object
          description: Monitoring and observability configuration
          properties:
            metrics_enabled:
              type: boolean
              default: true
            log_level:
              type: string
              enum: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
            trace_enabled:
              type: boolean
              default: false
              
        constraints:
          type: object
          description: Resource and policy constraints
          properties:
            max_tokens:
              type: integer
              minimum: 1
            max_cost_per_request:
              type: number
              minimum: 0
            allowed_models:
              type: array
              items:
                type: string
            requires_gpu:
              type: boolean
            privacy_mode:
              type: string
              enum: [public, private, local_only]

  # =====================================
  # COMPONENT DEFINITIONS
  # =====================================
  components:
    type: object
    description: Available components and their schemas
    properties:
      
      # Cloud API Components
      cloud_apis:
        type: object
        description: Cloud-based model API providers
        properties:
          
          openai_compatible:
            type: object
            description: OpenAI-compatible API providers (OpenAI, Together, Groq, etc.)
            properties:
              schema:
                type: object
                properties:
                  provider:
                    type: string
                    description: Provider name
                    enum: [openai, together, anyscale, perplexity, groq, mistral, deepseek, grok, fireworks, openrouter, custom]
                  api_key:
                    type: string
                    description: API key for authentication
                  base_url:
                    type: string
                    description: Custom base URL for the API
                  default_model:
                    type: string
                    description: Default model to use
                  timeout:
                    type: integer
                    minimum: 1
                    default: 60
                  max_retries:
                    type: integer
                    minimum: 0
                    default: 3
                  organization:
                    type: string
                    description: Organization ID (OpenAI specific)
                required: [provider]
              capabilities:
                type: array
                items:
                  type: string
                  enum: [chat, completion, embeddings, function_calling, vision, streaming]
              providers:
                type: object
                description: Provider-specific configurations
                
      # Model App Components
      model_apps:
        type: object
        description: Local model serving applications
        properties:
          
          ollama:
            type: object
            description: Ollama local model server
            properties:
              schema:
                type: object
                properties:
                  base_url:
                    type: string
                    default: http://localhost:11434
                  default_model:
                    type: string
                    default: llama3.2:3b
                  auto_start:
                    type: boolean
                    default: true
                  models:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        pull_on_start:
                          type: boolean
                  gpu_layers:
                    type: integer
                    minimum: 0
                  num_thread:
                    type: integer
                    minimum: 1
              capabilities:
                type: array
                items:
                  type: string
                  enum: [chat, embeddings, model_management, quantization]
                  
      # Fine-tuner Components  
      fine_tuners:
        type: object
        description: Model fine-tuning frameworks
        properties:
          
          pytorch:
            type: object
            description: PyTorch-based fine-tuning
            properties:
              schema:
                type: object
                properties:
                  # Hardware configuration - CRITICAL for cross-platform support
                  hardware:
                    type: object
                    description: Hardware-specific settings for optimal performance
                    properties:
                      device:
                        type: string
                        enum: [auto, cuda, mps, cpu]
                        default: auto
                        description: |
                          Device selection:
                          - auto: Automatically detect best available (recommended)
                          - cuda: NVIDIA GPU (Windows/Linux with CUDA)
                          - mps: Apple Silicon GPU (M1/M2/M3 Macs)
                          - cpu: CPU only (slowest but universal)
                      
                      memory_gb:
                        type: integer
                        minimum: 2
                        description: |
                          Available memory in GB:
                          - 4-8 GB: Use batch_size=1-2, gradient_checkpointing=true
                          - 8-16 GB: Use batch_size=2-4, standard settings
                          - 16+ GB: Use batch_size=4-8, can disable gradient_checkpointing
                      
                      precision:
                        type: object
                        description: Precision settings per hardware type
                        properties:
                          cuda:
                            type: object
                            properties:
                              use_fp16:
                                type: boolean
                                default: true
                                description: Use FP16 on CUDA (faster, less memory)
                              use_bf16:
                                type: boolean
                                default: false
                                description: Use BF16 if GPU supports it (A100, RTX 30xx+)
                              use_tf32:
                                type: boolean
                                default: true
                                description: Use TF32 on Ampere+ GPUs
                          mps:
                            type: object
                            properties:
                              use_fp16:
                                type: boolean
                                default: false
                                description: FP16 not well supported on MPS
                              use_bf16:
                                type: boolean
                                default: false
                                description: BF16 not supported on MPS
                          cpu:
                            type: object
                            properties:
                              use_fp16:
                                type: boolean
                                default: false
                                description: Keep FP32 on CPU for stability
                      
                      optimization:
                        type: object
                        description: Memory and speed optimizations
                        properties:
                          gradient_checkpointing:
                            type: boolean
                            default: true
                            description: |
                              Trade compute for memory:
                              - Enable for <8GB memory
                              - Disable for faster training with >16GB
                          gradient_accumulation_steps:
                            type: integer
                            minimum: 1
                            default: 1
                            description: |
                              Simulate larger batches:
                              - Use 4-8 for <8GB memory
                              - Use 1-2 for >16GB memory
                          mixed_precision:
                            type: string
                            enum: [no, fp16, bf16]
                            default: no
                            description: |
                              Mixed precision training:
                              - fp16: NVIDIA GPUs, saves memory
                              - bf16: Newer GPUs (A100, RTX 30xx+)
                              - no: CPU or compatibility mode
                  
                  base_model:
                    type: object
                    properties:
                      huggingface_id:
                        type: string
                      cache_dir:
                        type: string
                      torch_dtype:
                        type: string
                        enum: [auto, float32, float16, bfloat16]
                        description: |
                          Model loading precision:
                          - auto: Let PyTorch decide
                          - float32: Full precision (most memory)
                          - float16: Half precision (CUDA/MPS)
                          - bfloat16: Brain float (newer GPUs)
                  method:
                    type: object
                    properties:
                      type:
                        type: string
                        enum: [lora, qlora, full_finetune]
                      r:
                        type: integer
                        minimum: 1
                        maximum: 512
                      alpha:
                        type: integer
                        minimum: 1
                      dropout:
                        type: number
                        minimum: 0
                        maximum: 1
                  training:
                    type: object
                    properties:
                      batch_size:
                        type: integer
                        minimum: 1
                      learning_rate:
                        type: number
                        minimum: 0
                      num_epochs:
                        type: integer
                        minimum: 1
                      gradient_accumulation_steps:
                        type: integer
                        minimum: 1
                      warmup_ratio:
                        type: number
                        minimum: 0
                        maximum: 1
                      
          llamafactory:
            type: object
            description: LlamaFactory fine-tuning framework
            properties:
              schema:
                type: object
                properties:
                  model_name_or_path:
                    type: string
                  dataset:
                    type: string
                  template:
                    type: string
                  finetuning_type:
                    type: string
                    enum: [lora, qlora, full]
                  output_dir:
                    type: string
                    
      # Repository Components
      repositories:
        type: object
        description: Model repository integrations
        properties:
          
          huggingface:
            type: object
            description: HuggingFace Hub integration
            properties:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: HuggingFace API token
                  cache_dir:
                    type: string
                    description: Local cache directory
                  repo_id:
                    type: string
                    description: Repository identifier
                  private:
                    type: boolean
                    default: false

  # =====================================
  # STRATEGY TEMPLATES
  # =====================================
  strategy_templates:
    type: object
    description: Pre-defined strategy templates for common use cases
    properties:
      
      local_development:
        type: object
        description: Optimized for local development with Ollama
        
      cloud_production:
        type: object
        description: Production deployment with cloud APIs
        
      hybrid_fallback:
        type: object
        description: Cloud primary with local fallback
        
      fine_tuning_pipeline:
        type: object
        description: Complete fine-tuning workflow
        
      multi_provider:
        type: object
        description: Load-balanced multi-provider setup
        
      cost_optimized:
        type: object
        description: Minimize costs while maintaining quality
        
      privacy_first:
        type: object
        description: Local-only processing for sensitive data
        
      research_experimentation:
        type: object
        description: Flexible setup for model research

  # =====================================
  # USE CASE MAPPINGS
  # =====================================
  use_case_mapping:
    type: object
    description: Maps use cases to recommended strategies
    properties:
      
      chatbot:
        type: array
        items:
          type: string
        default: [hybrid_fallback, cloud_production]
        
      code_generation:
        type: array
        items:
          type: string
        default: [cloud_production, specialized_models]
        
      document_analysis:
        type: array
        items:
          type: string
        default: [local_development, privacy_first]
        
      creative_writing:
        type: array
        items:
          type: string
        default: [cloud_production, fine_tuned_models]
        
      translation:
        type: array
        items:
          type: string
        default: [multi_lingual, cloud_production]
        
      summarization:
        type: array
        items:
          type: string
        default: [cost_optimized, hybrid_fallback]

  # =====================================
  # VALIDATION RULES
  # =====================================
  validation_rules:
    type: object
    description: System-wide validation constraints
    properties:
      
      required_components:
        type: array
        description: Components required for valid configuration
        items:
          type: string
          
      incompatible_combinations:
        type: array
        description: Component combinations that are not allowed
        items:
          type: object
          properties:
            components:
              type: array
              items:
                type: string
            reason:
              type: string
              
      performance_thresholds:
        type: object
        properties:
          max_latency_ms:
            type: integer
            minimum: 1
          min_throughput_rps:
            type: number
            minimum: 0
          max_error_rate:
            type: number
            minimum: 0
            maximum: 1

  # =====================================
  # METADATA
  # =====================================
  metadata:
    type: object
    description: Schema metadata and versioning
    properties:
      version:
        type: string
        pattern: ^\d+\.\d+\.\d+$
      last_updated:
        type: string
        format: date-time
      maintainers:
        type: array
        items:
          type: string
      documentation_url:
        type: string
        format: uri

# Required top-level properties
required: [strategies, components]

# Additional schema constraints
additionalProperties: false